SCIInstitute/ShapeWorks

Run/source/ITKParticleSystem/itkParticleEnsembleEntropyFunction.txx
Run/source/ITKParticleSystem/itkParticleMeshBasedGeneralEntropyGradientFunction.txx

removed the construction of inverse covariance matrix as a big identity matrix num_points*3 x num_points*3 for mean energy-based updates

vnl bug for big matrices

---

UseCaseDocumentation/LAMain.py

We can now catch exceptions and use `subprocess.check_call` instead of `os.system`. It's unwise to be using `shell=True` but the commands themselves need to be transformed into arrays in order to make that change.

add ability to catch a keyboard interrupt to the LAMain.zip use case

---

ExternalLibs/trimesh2/include/MapFilter.h
ExternalLibs/trimesh2/include/MapFilter.hxx
ExternalLibs/trimesh2/include/ReduceFilter.h
ExternalLibs/trimesh2/include/ReduceFilter.hxx

Also fix ITK names.
This should fix the crash in GenerateFidsFilesFromMeshes (issue #243)

Disable ITK5 dynamic multithreading for MapFilter and ReduceFilter.

---

Libs/Optimize/ParticleSystem/itkParticleProcrustesRegistration.cxx
Libs/Optimize/ParticleSystem/itkParticleProcrustesRegistration.h
Libs/Optimize/ShapeWorksRunApp.txx
Studio/src/Optimize/ShapeWorksOptimize.cxx

The diffs associated show all uses of SetComputeTransformationOn/Off since I have removed them and it all compiles.

Fix procrustes

---

BUILD.md
CMake/DefaultBuildType.cmake
CMakeLists.txt
conda_installs.sh

… polluted by pip installs; install ncurses to ensure ccmake works in this environment (broken due to version associated with python 3.5); add default build type (Debug if using a git clone, Release otherwise, and neither when generator allows build type to be selected); don't make install since it is currently broken, takes forever to do it for Studio, and isn't needed for development; clarify branch checkout vs creation in BUILD.md instructions (fix issue #261)

fix conda_installs, disable (broken, time-consuming) make install by default, set default build type, and improve build instructions

---

Studio/src/Application/Data/Mesh.cc

The fix is very easy for Studio since we have a single point of import we can just convert to RAI.

Fix LPI (and other) oriented volumes in Studio

---

conda_installs.sh

fix conda_installs.sh
- returns failure if any of the installation commands fail; 
- add channels in priority order so they aren't specified on each install command (which automatically alters priority); 
- install pip as part of the sub-environment where it belongs; 
- update conda using default channels rather than base
Thanks @archanasri for trying out this script and finding the missing git-lfs which motivated its improvement!

fix conda_installs.sh w/ versions

---

Python/DatasetUtilsPackage/DatasetUtils/GirderConnector.py

Use streaming download for getting use case data from girder.
This avoids overloading memory when downloading large files (several GB)
#278

Streaming dataset download

---

Examples/Python/OptimizeUtils.py
Examples/Python/README.md

Small changes for missing variables in Python script.
Probably unrelated here, but the Python script crashed at a later step because ShapeWorks Studio was missing: the default option in CMake is to not build Studio.

Fix errors in ellipsoid example

---

BUILD.md
CMakeLists.txt
GettingStarted.md
README.md
superbuild.sh

Changed Build.md to be more straight-forward and detailed.
Move PATH instructions to GettingStarted.md
Improve CMake error messages.
superbuild.sh: Always set VTK_DIR to the path with lib instead of lib64: VTK_DIR=${INSTALL_DIR}/lib/cmake/vtk-${VTK_VER_STR}

Update build instructions

---

Studio/src/Application/CMakeLists.txt
Studio/src/Application/Resources/Info.plist.in

This fixes the Mac bundle for Studio in a couple of ways.  First, we were missing the bundle identifier, and second, this sets the bundle as non-relocatable.  More here:
https://scriptingosx.com/2017/05/relocatable-package-installers-and-quickpkg-update/
I believe this was causing the problem we were seeing on a Catalina system, but I don't think it had anything to do with Catalina after all.  What I believe happened is that it updated some other app bundles elsewhere on the system (possibly another copy of Studio) instead.

Fix mac package

---

Studio/src/Application/Data/Project.cc
Studio/src/Application/Visualization/ShapeWorksStudioApp.cc

Fixes #340 by:
1. Detect the invalid XML file and print a warning rather than crash.
2. Disable writing of these XML files if the save action is disabled.

Fix studio crash 340

---

ExternalLibs/trimesh2/include/TriMesh.h
Libs/Alignment/ApplyRigid3DTransformationToImage.cxx
Libs/Alignment/ICPRigid3DImageRegistration.cxx
Libs/Alignment/ResampleVolumeToIsotropic.cxx
Libs/Alignment/ResizeOriginResampleVolumes.cxx
Libs/Alignment/TranslateImages.cxx
Libs/Alignment/TranslateShapeToImageOrigin.cxx
Libs/Image/ClipVolume.cxx
Libs/Image/CloseHoles.cxx
Libs/Image/CropImages.cxx
Libs/Image/ExtractGivenLabelImage.cxx
Libs/Image/FastMarching.cxx
Libs/Image/ReflectVolumes.cxx
Libs/Image/ThresholdImages.cxx
Libs/Image/TopologyPreservingSmoothing.cxx
Libs/Mesh/GenerateBinaryAndDTImagesFromMeshes.cxx
Libs/Mesh/GenerateFidsFilesFromMeshes.cxx
Libs/Mesh/GetFeatureVolume.cxx
Libs/Mesh/RemoveFidsDTLeakage.cxx
Testing/OptimizeTests/OptimizeTests.cpp

Enabled compression on ITK image writers wherever I could find them in the code.  This should save time and space.

Enable ITK writer compression on itk::ImageFileWriters

---

CMakeLists.txt
superbuild.sh

We're having a problem that the eigen build is wrong for windows:
2020-02-19T18:58:26.9726289Z -- Configuring done
2020-02-19T18:58:31.6609916Z -- Generating done
2020-02-19T18:58:31.7035254Z -- Build files have been written to: D:/a/bdeps/eigen/build
2020-02-19T18:58:31.9449568Z mingw32-make: *** No rule to make target 'install'.  Stop.
However, for some reason this isn't aborting the github action and furthermore, the compile of shapeworks actually works.  But it does not cache correctly, so subsequent builds using the cache will fail.

Attempting to fix eigen build on windows.

---

Applications/shapeworks/Commands.cpp
Applications/shapeworks/Executable.cpp
Libs/Image/Image.cpp

Fixed typo, moved second line of long description to match indent, added newline between command groups.
Before:
After:

Fix typos and layout of 'shapeworks' usage

---

Examples/Python/AnalyzeUtils.py
Examples/Python/GroomUtils.py

Was getting the following error:
```
Continuing to groom.
Traceback (most recent call last):
File "RunUseCase.py", line 54, in <module>
module.Run_Pipeline(args)
File "D:\Workspace\ShapeWorks\ShapeWorks\Examples\Python\femur.py", line 143, in Run_Pipeline
reflectedFiles_mesh, reflectedFile_img = anatomyPairsToSingles(parentDir + 'reflected', files_mesh, files_img, reference_side)
File "D:\Workspace\ShapeWorks\ShapeWorks\Examples\Python\GroomUtils.py", line 536, in anatomyPairsToSingles
img_name = img.rsplit(os.sep, 1)[1]
IndexError: list index out of range
```
The file paths look like this: `TestFemur/femur/images/m03_1x_hip.nrrd`
But we are trying to split using \ as a delimiter on Windows.
Should just always use / since windows allows using either for file paths.
I fixed it by changing …

Use forward slash instead of os.sep to split string path up in groom utils

---

.github/workflows/build-windows.yml
CMakeLists.txt
Testing/CMakeLists.txt
Testing/ImageTests/CMakeLists.txt
Testing/MeshTests/CMakeLists.txt
Testing/OptimizeTests/CMakeLists.txt
Testing/ParticlesTests/CMakeLists.txt
Testing/PythonTests/CMakeLists.txt
conda_installs.sh

You don't have to re-run conda_installs (but it's in there), just run:
`conda install gtest`
It's very fast and dependency-free.
This will break the GitHub actions since I don't think they use conda_installs.sh.

use conda for gtest rather than downloading it every time cmake is run

---

Libs/Optimize/Optimize.cpp
Libs/Optimize/ParticleSystem/itkMaximumEntropySurfaceSampler.txx
Libs/Optimize/ParticleSystem/itkParticleImageDomain.h

This PR adds a few extra APIs to ParticleImageDomain so that the Optimizer and other classes don't do `domain->GetImage() ...`. This is a subset of the changes I've made for OpenVDB, and would be required to get the Optimizer to work with arbitrary domains(such as meshes).
(Note that the UpdateSurfaceArea function does not work currently. It is needed by ModifiedContangentGradientFunction, which hasn't been tested recently.)
@0leks does this cover everything you need?

Refactor ImageDomain

---

Applications/shapeworks/Commands.cpp

I forgot to remove this from the usage before when we merged it with --name

Removed --dicom_dir as we not longer use/have it.

---

Examples/Python/GroomUtils.py
Examples/Python/ellipsoid.py
Examples/Python/femur.py
Examples/Python/left_atrium.py
Testing/PythonTests/PythonTests.cpp

I removed the recenter call from applyIsotropicResampling in GroomUtils.py and had the use cases call the "center" function in GroomUtils if they needed it. I also fixed the girder naming issue Alan mentioned for the femur use case.
I tested this on all of the use cases and this change did not effect the results.

Separate centering resampling

---

Studio/src/Application/Visualization/ShapeWorksStudioApp.cc
Studio/src/Application/Visualization/ShapeWorksStudioApp.h
Studio/src/Application/Visualization/ShapeWorksStudioApp.ui
Studio/src/Application/Visualization/Visualizer.cc
Studio/src/Application/Visualization/Visualizer.h

This PR adds two menu options to Studio.  There is a current mesh export and also current mesh scalars output.
To use with group differences, make sure you have the group differences displayed, then choose "Export Mesh Scalars"
The CSV file written will have a column "scalar_values".

Studio: Add export of current mesh as VTK and also scalars as CSV.

---

Libs/Optimize/CMakeLists.txt
Libs/Optimize/ParticleSystem/itkParticleEnsembleEntropyFunction.h
Libs/Optimize/ParticleSystem/itkParticleEnsembleEntropyFunction.txx
Libs/Optimize/ParticleSystem/itkParticleMeshBasedGeneralEntropyGradientFunction.txx
Libs/Utils/CMakeLists.txt
Libs/Utils/Utils.cpp
Libs/Utils/Utils.h
build_dependencies.sh

This reduces memory usage in itkParticleGeneralMeshBasedGeneralEntropyGradientFunction when mesh_attributes is enabled. Avoids some copies, some allocations, and reordered/expanded matrix operations to run faster. In the pelvis case, memory requirement for the particle system has reduced from ~14GB to ~5GB. Iteration time seems to have reduced by about 50% in the same use case.
Same fixes implemented in itkParticleEnsembleEntropyFunction.

Reduce memory usage in inverse covariance matrix

---

CMakeLists.txt
build_dependencies.sh

Make it so path to FindOpenVDB.cmake isn't needed when using build_dependencies. 
*NOTE*: this also corrects a typo in the config string printed by build_dependencies.sh, which means it will rebuild everything. So maybe merge it after everyone has gone to bed. :)

Simplify build

---

Examples/Python/CommonUtils.py
Examples/Python/GroomUtils.py

I have edited the "FindReferenceImage" function to take care of different image sizes and prevent loading all the images into memory.  I have tested on LA data.
For sampling a subset of data the "sampledata" is changed to just read two images at a time and run spectral clustering based on the distance matrix of input images. 
@jadie1  Could you please test this two functions for the femur data as well.

Fix la memory

---

Support/package.sh
Support/package_windows.sh

Using the tag is problematic with the automatic release action.  The problem is that all three platforms will get the same tag that will be something like "dev-linux-31", even on mac/windows.  So I've changed the packaging scripts to just use "dev" for the master branch.

Fix naming of assets for development releases

---

Libs/Particles/itkParticleShapeStatistics.cpp
Libs/Project/Project.cpp
Studio/src/Application/Analysis/AnalysisTool.cpp
Studio/src/Application/Analysis/AnalysisTool.h
Studio/src/Application/Analysis/AnalysisTool.ui
Studio/src/Application/Data/LegacyMeshGenerator.cpp
Studio/src/Application/Data/Mesh.cpp
Studio/src/Application/Data/Session.cpp
Studio/src/Application/Data/Session.h
Studio/src/Application/Optimize/OptimizeTool.cpp
Studio/src/Application/Visualization/Lightbox.cpp
Studio/src/Application/Visualization/Lightbox.h
Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp
Studio/src/Application/Visualization/ShapeWorksStudioApp.h
Studio/src/Application/Visualization/ShapeWorksStudioApp.ui
Studio/src/Application/Visualization/Viewer.cpp
Studio/src/Application/Visualization/Visualizer.cpp
Studio/src/Application/Visualization/Visualizer.h

This PR makes the following changes:
* Enable save after save-as from a new/unsaved project
* Fix save-as default location
* Fix "display sample" mode when in analysis
* Fix "export current mesh" (was not working with updated data structures)
* Added PCA raw component score export to Studio (was only in View2 previously)

Studio updates

---

Libs/Optimize/Optimize.cpp
Libs/Optimize/Optimize.h

Currently seeded with 42.  This gives us a cross-platform reproducible PRNG.

Replace srand/rand with C++11 Mersenne Twister 19937

---

Libs/Particles/ShapeEvaluation.cpp

@akenmorris with this change, valgrind stops complaining. Could you check if it works on Mac?
If this solves the issue, do you think its an issue with Eigen dropping memory it shouldn't, or our usage of the function? I can't see anything about this usage pattern [on their docs](https://eigen.tuxfamily.org/dox/group__TutorialBlockOperations.html).

Fix specificity memory issue

---

Libs/Mesh/CMakeLists.txt
Testing/MeshTests/MeshTests.cpp

This PR fixes the unit tests by removing the 'main' from GroomFemur.cpp from LibMesh.
Resolves #717

Fix main/unit tests

---

Python/DatasetUtilsPackage/DatasetUtils/GirderAPI.py

The API call I was using to get list of items has a default limit of 50. 
There doesn't seem to be a way to remove the limit so I set arbitrarily large limit of 99999

Set arbitrarily large limit when querying for item list.

---

Examples/Python/.gitignore
Examples/Python/ellipsoid.py
Examples/Python/ellipsoid_fd.py
Examples/Python/lumps.py

The data folder should now be considered read-only for these three use cases (the usecase won't re-unzip unless the data folder is missing)
Tested:

cleaning up dataset download/unzip logic for ellipsoid,lumps

---

Testing/data/cutting_plane/cutting_plane.xml
Testing/data/fixed_domain/fixed_domain.xml
Testing/data/hemisphere/hemisphere.xml
Testing/data/sphere/sphere.xml

This PR cuts the verbosity of the OptimizeTests down to 0.

Set verbosity to 0 for OptimizeTests

---

Libs/Optimize/Optimize.cpp
Libs/Optimize/Optimize.h
Libs/Optimize/OptimizeParameterFile.cpp
Libs/Optimize/ParticleSystem/MeshDomain.h
Libs/Optimize/ParticleSystem/OptimizationVisualizer.cpp
Libs/Optimize/ParticleSystem/OptimizationVisualizer.h
Libs/Optimize/ParticleSystem/Sampler.cpp
Libs/Optimize/ParticleSystem/Sampler.h
Libs/Optimize/ParticleSystem/TriMeshWrapper.cpp
Libs/Optimize/ParticleSystem/TriMeshWrapper.h
Libs/Optimize/ParticleSystem/itkParticleGradientDescentPositionOptimizer.txx
Libs/Optimize/ParticleSystem/itkParticleMeshBasedGeneralEntropyGradientFunction.txx

This PR changes out OpenMP for TBB.  The main driver for this is to enable multithreading on Mac, which doesn't support OpenMP (at least not without great difficulty).  TBB has a nearly equivalent parallel-for construct.  I would prefer to use C++17's parallel-for, but we are compiling as C++14 for now (due to limited C++17 support on some platforms).  TBB may also allow us more control over threading than OpenMP should we choose to further parallelize the code.
* Note: This does not add an additional dependency as we already had TBB as a sub-dependency of OpenVDB.
* Diff of point files shows this to be identical before/after.  I did not run *all* the use cases, but I don't there is no reason to think that there would be a difference.
* Speed on windows/linux seems comparable (or faster). …

Optimizer switch to TBB

---

Libs/Optimize/Optimize.cpp
Libs/Optimize/Optimize.h
Testing/data/hemisphere/hemisphere.xml

This PR revamps the checkpointing to make it more organized and handle multiscale better.  We now have a "checkpoints" directory in the output directory.  Inside will be folders such as:
p02_init_iter010
...
p64_opt_iter900
The format, is, now with leading padded zeros:
P<particle count>_<init/opt>_iter<iteration number>
This PR also fixes a bug in the initialization where an uninitialized point is used to find the first location.  If this undefined value is NaN it can cause this initial position to fail.  This was causing the Mac GH action to hang on open_mesh_test.  Setting the point to [0,0,0] fixes it.

Revamp checkpointing.

---

Examples/Python/CommonUtils.py
Examples/Python/ellipsoid.py
Examples/Python/ellipsoid_cut.py
Examples/Python/ellipsoid_mesh.py
Examples/Python/femur.py
Examples/Python/femur_cut.py
Examples/Python/femur_mesh.py
Examples/Python/left_atrium.py
Examples/Python/lumps.py

Updated use cases to:
- Include a tiny test which always runs on the first 3 shapes (issue #789)
- Include the option to run on a subset of the shapes based on clustering on segs or meshes (issue #790)
- Updated documentation on mkdocs branch to specify these options are necessary in new-use-case.md 
The only use case which does not have these options is the ellipsoid fixed domains because these options don't make sense in that context. 
To test tiny_test run:
`python RunUseCase.py --use_case <use_case> --tiny_test`
To test subsampling run:
`python RunUseCase.py --use_case <use_case> --use_subsample --num_subsample <integer>`
(Defaults to 3 if `num_subsample` is not specified)

Use case tiny test and subsampling

---

Libs/Optimize/Optimize.cpp
Libs/Optimize/ParticleSystem/MeshDomain.cpp
Libs/Optimize/ParticleSystem/MeshDomain.h
Libs/Optimize/ParticleSystem/MeshWrapper.h
Libs/Optimize/ParticleSystem/TriMeshWrapper.cpp
Libs/Optimize/ParticleSystem/TriMeshWrapper.h
Libs/Optimize/ParticleSystem/itkParticleConstrainedModifiedCotangentEntropyGradientFunction.txx
Libs/Optimize/ParticleSystem/itkParticleCurvatureEntropyGradientFunction.txx
Libs/Optimize/ParticleSystem/itkParticleDomain.h
Libs/Optimize/ParticleSystem/itkParticleEntropyGradientFunction.h
Libs/Optimize/ParticleSystem/itkParticleEntropyGradientFunction.txx
Libs/Optimize/ParticleSystem/itkParticleGeneralShapeGradientMatrix.h
Libs/Optimize/ParticleSystem/itkParticleGeneralShapeMatrix.h
Libs/Optimize/ParticleSystem/itkParticleGoodBadAssessment.txx
Libs/Optimize/ParticleSystem/itkParticleGradientDescentPositionOptimizer.txx
Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
Libs/Optimize/ParticleSystem/itkParticleImageDomainWithCurvature.h
Libs/Optimize/ParticleSystem/itkParticleImageDomainWithGradients.h
Libs/Optimize/ParticleSystem/itkParticleImageDomainWithHessians.h
Libs/Optimize/ParticleSystem/itkParticleImplicitSurfaceDomain.h
Libs/Optimize/ParticleSystem/itkParticleImplicitSurfaceDomain.txx
Libs/Optimize/ParticleSystem/itkParticleMeanCurvatureAttribute.h
Libs/Optimize/ParticleSystem/itkParticleNeighborhood.h
Libs/Optimize/ParticleSystem/itkParticleOmegaGradientFunction.txx
Libs/Optimize/ParticleSystem/itkParticleRegionNeighborhood.h
Libs/Optimize/ParticleSystem/itkParticleRegionNeighborhood.txx
Libs/Optimize/ParticleSystem/itkParticleSurfaceNeighborhood.h
Libs/Optimize/ParticleSystem/itkParticleSurfaceNeighborhood.txx
Libs/Optimize/ParticleSystem/itkParticleSystem.h
Libs/Optimize/ParticleSystem/itkParticleSystem.txx

This PR modifies many APIs to pass around particle index along with position. This is only useful for the mesh domain right now: to store a cache of particle index -> triangle index. This prevents many expensive KDtree lookups, resulting in a speedup(1:35 hours to 0:50 hours in femur_mesh use case)

Cache particle -> triangle index

---

Libs/Optimize/ParticleSystem/itkParticleContainer.h
Libs/Optimize/ParticleSystem/itkParticleGradientDescentPositionOptimizer.txx
Libs/Optimize/ParticleSystem/itkParticleRegionNeighborhood.h
Libs/Optimize/ParticleSystem/itkParticleRegionNeighborhood.txx
Libs/Optimize/ParticleSystem/itkParticleSystem.txx

Replaces std::map in ParticleContainer with std::vector, results in faster optimization(femur_mesh in 38 minutes vs 50 minutes). Tested on ellipsoid(image domain), works correctly there.
Note that this builds on the cachewhichtri branch, so the PR diff looks huger than it really is. See https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer for the changes
Specifically, note the [removal of the Erase function](https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer#diff-f16703aff672f1a54739e4c2cedc11271f53075609dea00ba557574b64e03bbfL131) and the [removal of its usage in ParticleNeighborhood](https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer#diff-0b01cf01f36bdccbd15ce6edc67286dc3fe97f6e161f75d9cfc …

Remove std::map from ParticleContainer

---

.github/workflows/build-linux.yml
.github/workflows/build-windows.yml
CMake/FindLIBIGL.cmake
CMakeLists.txt
build_dependencies.sh

This is a very small PR which includes the download for libigl via `build_dependencies.sh` script.
Additionally, I included the include path to the header files to the libigl in the `CMakeLists.txt`.
To include any libigl function we just perform 
``` #include <igl/function.h>```
Here is a simple test which can be performed to check, execute this snippet of code after adding the appropriate changes to the CMake for adding a new script
```
#include <igl/cotmatrix.h>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <iostream>
int main()
{
Eigen::MatrixXd V(4,2);
V<<0,0,
1,0,
1,1,
0,1;
Eigen::MatrixXi F(2,3);
F<<0,1,2,
0,2,3;
Eigen::SparseMatrix<double> L;
igl::cotmatrix(V,F,L);
std::cout<<"Hello, mesh: "<<std::endl<<L*V<<std::endl;
return 0;
}
```
I have tried this out and it works. …

Libigl build included

---

.github/workflows/build-linux.yml
.github/workflows/build-mac.yml
.github/workflows/build-windows.yml
Support/package.sh
Support/package_windows.sh

This PR modifies the version naming for artifacts built from PR.  PRs will now have the form:
VERSION="ShapeWorks-PR-${PR_NUMBER}-${PLATFORM}"
They were previous using the tag mode, but this was typically just "dev-linux" (on any platform) and a not very useful git hash from the merge commit.

PR package naming

---

conda_installs.sh

The only solutions I can find for this problem are to either re-install (not applicable) or do this ln operation in the env lib dir:
`ln -s libffi.7.dylib libffi.6.dylib`
I have no idea why, but sometimes we end up with 7 and other times with 6 and pip always needs 6.
Relevant links:
https://github.com/conda/conda/issues/9038
https://github.com/conda/conda/issues/9899
9038 was closed for some reason.  9899 is still open.

Fix broken conda installs on GitHub Actions (mac)

---

Examples/Python/notebooks/tutorials/getting-started-with-exploring-segmentations.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-grooming-segmentations.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-meshes.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-segmentations.ipynb
Examples/Python/notebooks/tutorials/setting-up-shapeworks-environment.ipynb
Examples/Python/setupenv.py
Support/package.sh
conda_installs.sh

This PR fixes the loader path for the shapeworks python module on Mac OS.
It also fixes conda_installs.sh for the Mac binary deployment.
The change to the `setting-up-shapeworks-environment.ipynb` should fix this script to run on the binary deployments of Mac, Linux and Windows without the user needing to change the path variables.  If this works, I suppose we need to change the rest of the notebooks, although I would suggest that this logic be moved to the setupenv.py script, but it will require changing the behavior, so I have not done so yet.

Fix python deployment

---

Libs/Mesh/PreviewMeshQC/FEAreaCoverage.cpp
Libs/Mesh/PreviewMeshQC/FEAreaCoverage.h

The ignore-back-intersection flag decides whether or not to include back-intersections in coverage calculation.

Added ignore-back-intersection flag to FEAreaCoverage

---

Libs/Mesh/PreviewMeshQC/FEAreaCoverage.cpp
Libs/Mesh/PreviewMeshQC/FEAreaCoverage.h

- Modified algorithm so it looks for closest intersection (previously, first intersection was chosen)
- Added angle threshold parameter: This is used to see if the normal at the intersection point does not deviate too far from the ray. (Value should be between 0 and 1, which represents negative cosine of angle)
- Added back search radius parameter: This limits back intersections to user specified value.

Improvements to FEAreaCoverage tool

---

Libs/Particles/ShapeEvaluation.cpp
Testing/data/shapeevaluation.txt
Testing/shapeworksTests/shapeevaluation.sh
Testing/shapeworksTests/shapeworksTests.cpp

This PR adds a test for particle system subcommands in shapeworksTests.
Closes #602

Add test for shape evaluation shapeworks subcommand

---

Examples/Python/GroomUtils.py
Examples/Python/ellipsoid.py
Examples/Python/ellipsoid_cut.py
Examples/Python/femur.py
Examples/Python/femur_cut.py
Examples/Python/left_atrium.py

This PR adds rigid alignment to the grooming pipeline in segmentation based use cases - issue #826 
This PR also changes the ellipsoid case to use ellipsoid-v2 data which is not already groomed to provide a better demonstration of grooming. It changes ellipsoid_cut to use ellipsoid-aligned-v0 which is already aligned. The grooming steps except creating distance transforms are removed so that the use case highlights the cutting plane and does not repeat the ellipsoid use case. 
To test run the following use cases:
- ellispoid
- ellipsoid_cut
- femur (with and without grooming images)
- femur_cut (with and without grooming images)
- left_atrium (with and without grooming images)

Rigid Alignment

---

.github/workflows/build-linux.yml
.github/workflows/build-mac.yml
.github/workflows/build-windows.yml
build_dependencies.sh

Explicitly set RelWithDebInfo for dependencies and SW build for all platforms for binary deployments from GH Actions.
Resolves #928 
This should help with bugs like #925

Add --build-type<type> to build_dependencies.sh, set default to RelWithDebInfo

---

Applications/shapeworks/Commands.cpp
Applications/shapeworks/Commands.h
Applications/shapeworks/shapeworks.cpp
Libs/Mesh/Mesh.cpp
Libs/Mesh/Mesh.h
Testing/MeshTests/MeshTests.cpp
Testing/data/invertnormals.vtk

This PR adds a test for the invert-normals command.
Additionally, this adds a check over the face indices for Mesh::operator== 
Closes #937

Invert normals test

---

Studio/src/Application/Analysis/AnalysisTool.cpp
Studio/src/Application/Analysis/AnalysisTool.h
Studio/src/Application/Data/Shape.cpp
Studio/src/Application/Optimize/OptimizeTool.cpp
Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp

Resolves the following issues:
#961 - Studio: Sample display bug
#960 - Studio: Only display basename of file name 
#959 - Studio: When optimization is aborted, the file menu does not re-enable
#963 - Studio: Bug when switching out of analysis while PCA animation is running

Studio fixes

---

build_dependencies.sh

This PR should fix #964 by switching to a fixed version of LibIGL
A simple dataset exhibiting the bug is found on the #964 description.  Using this branch (must call build_dependencies.sh again to check out the new libigl), this bug should be fixed.

Fix #964 by targeting fixed libigl fork.

---

Studio/src/Application/Optimize/OptimizeTool.cpp
Studio/src/Application/Optimize/OptimizeTool.h
Studio/src/Application/Optimize/OptimizeTool.ui

Resolve #1031 
Rather than use QDoubleSpinBoxes for these values that must have a number of decimals set, I've switched to free response line edits with validators.  When a param is invalid, the background changes to red and the "run optimize" button disables.  This allows the user to easily type "1e9" for a value as they support scientific notation for the double parameters.

Relax optimize input constraints in Studio

---

Libs/Optimize/ParticleSystem/MeshDomain.h
Libs/Optimize/ParticleSystem/Sampler.cpp

Make sure MeshDomain uses the itk Smart Pointer so there are no memory leaks
Closes #1044

fix memory leak in Sampler::AddMesh()

---

Studio/src/Application/Analysis/AnalysisTool.cpp
Studio/src/Application/Data/MeshManager.cpp
Studio/src/Application/Data/MeshManager.h

Fix #1045 by adding an additional check and fall back when groomed mesh is missing while looking for reference mesh for mesh warping.

Fix studio missing groom (#1045)

---

Studio/src/Application/Analysis/AnalysisTool.cpp
Studio/src/Application/Analysis/AnalysisTool.ui
Studio/src/Application/Visualization/BarGraph.cpp

This PR fixes #1030, updating the 1 based instead of 0 based indexing for modes.
I also added the current mode's explained variance and cumulative explained variance under the lambda value:
Docs updated!

Studio variance mode

---

Examples/Python/notebooks/tutorials/getting-started-with-grooming-segmentations.ipynb

Very small fix of notebook on windows. Not enough to warrant creating the next RC yet.
Confirmed this works on Windows, but haven't checked other platforms.

Path class must be explicitly converted to string when used as such (#1112)

---

conda_installs.bat

Removing nbstripout lines from conda_installs.bat that won't work on non-git repos.  

---

Examples/Python/ellipsoid_cut.py

This PR fixes the parameters of the ellipsoid_cut use case so that the correspondence is reasonable. I decreased the number of particles because the clipped ellipsoid, which had less than 1/4 of the surface area of the whole ellipsoid was using the same number of particles (128 -> 32). I also increased the number of iterations so that the particles have the chance to swap in the cramped space of particles. This fixes issue #1104. The results are shown in fig 1
Fig. 1 Shows the result of running the use case with the new parameters
To run this use case
1. cd into ShapeWorks/Examples/Python
2. `python RunUseCase.py --use_case ellipsoid_cut`

Tuned parameters to fix the ellipsoid_cut use case

---

Examples/Python/notebooks/tutorials/getting-started-with-grooming-segmentations.ipynb

launch studio using list of files since on windows it doesn't support wildcard arguments
- note that getting started notebook still fails on OS X, a recent discovery, but this is not related to this fix

fix getting started with grooming segmentations notebook

---

conda_installs.sh

This should be in line with the rest of the script using the analogous `--yes` flags.
https://docs.anaconda.com/anaconda/install/silent-mode/#linux-macos

Install Miniconda in non-interactive mode

---

Studio/src/Application/Visualization/Viewer.cpp

Studio scalar bar label precision

---

build_dependencies.sh

Failed due to a file called `version` in one of the xlnt third party libs. Fixed by temporarily moving that file out of the way to build the library then back afterwards (in case it's needed for anything, which seems unlikely.

fix osx Big Sur dependencies xlnt build and upgrade it to version 1.5.0

---

Applications/shapeworks/MeshCommands.cpp
Libs/Mesh/CMakeLists.txt
Libs/Mesh/MeshWarper.h

Updates the` warp-mesh` command to handle warping multiple meshes at once utilizing the same reference mesh and points.
Usage:
- For single warp, it it the same usage `shapeworks warp-mesh --reference_mesh=template.ply --reference_points=template.particles --target_points=output.particles --target_mesh=output.vtk`
- For multiple point files set `--multiple` tag to be true (false by default) and pass a txt file of target point paths and target mesh paths. `shapeworks warp-mesh --reference_mesh=template.ply --reference_points=template.particles --target_points=output_particles.txt --target_mesh=output_meshes.txt --multiple=true`

Mesh Warping for Multiple Meshes

---

Examples/Python/RunUseCase.py
Examples/Python/deep_ssm.py
Python/DeepSSMUtilsPackage/DeepSSMUtils/__init__.py
Python/DeepSSMUtilsPackage/DeepSSMUtils/eval_utils.py
Python/DeepSSMUtilsPackage/DeepSSMUtils/loaders.py
Testing/UseCaseTests/UseCaseTests.cpp

This PR addresses:
- Issue #1105 Refactoring DeepSSM to use a config file
- Issue #1223 Fixing surface to surface distance in eval
- Updates getting meshes from distance transforms to use pybind `toImage()` instead of command line `MeshFromDistanceTransforms`
- Updates getting meshes from particles to use `mesh-warp` instead of `ReconstructSurface`
- Updates use case to print warning but still run on CPU rather than exiting
- Improves the tiny test so it runs in about 2 min
To test, run the tiny test or the full use case (both should run on GPU or CPU). 
This will probably require running:
`pip install Python/DeepSSMUtilsPackage/` 
`pip install Python/DataAugmentationUtilsPackage/`

DeepSSM Updates

---

Libs/Python/ShapeworksPython.cpp
Testing/PythonTests/PythonTests.cpp
Testing/PythonTests/findReferenceMesh.py

This adds a python API for MeshUtils::findReferenceMesh and a python test as well.

Add python API for MeshUtils::findReferenceMesh

---

Python/shapeworks/shapeworks/__init__.py
Python/shapeworks/shapeworks/utils.py

Addresses issue #1247
Updates find_reference_image_index() to convert the segmentations to meshes and use sw.MeshUtils.findReferenceMesh() to select reference. 
Removes find_reference_mesh_index() because it wasn't being used anywhere and now sw.MeshUtils.findReferenceMesh() can be used directly.

Updating reference selection

---

.github/workflows/build-linux.yml
.github/workflows/build-mac.yml
.github/workflows/build-windows.yml
Python/shapeworks/shapeworks/__init__.py
Support/package.sh
Support/shapeworks.nsi
conda_installs.bat
conda_installs.sh
install_python_module.bat
install_python_module.sh

- install python module by copying cython and company to the conda install path; 
- no longer need PYTHONPATH to import shapeworks

user python module installation during conda_installs for all three platforms

---

Support/osxscripts/preinstall
Support/package.sh

Address #1296.
This won't work if the user hasn't installed it on their main volume.  I'm wary of using the undocumented $DSTROOT which seems to point to the right place, but without guarantees I don't want to remove it if it could be wrong.

Add OSX preinstall script to remove /Application/ShapeWorks

---

build_dependencies.sh
docs/dev/build.md

- provide complete Windows build command when build_dependencies.sh finishes; 
- update build instructions in docs
I validated the modifications to build_dependencies.sh, that show Windows build instructions upon completion, work correctly by running it again on Windows.

build windows 

---

Libs/Project/Project.cpp

Fix #1368 by using the "highest_row" rather than the number of rows.  Some spreadsheets written by LibreOffice apparently write out that they use the full million row range even though they don't.  The "ws.rows" will return a range going to a million and iterating over this many times is a problem.

Fix #1368  spreadsheet hanging on load.

---

.github/workflows/Dockerfile
.github/workflows/build-linux.yml

Ubuntu 16 GitHub Action Runner will be removed in September 2021.  This PR switches to ubuntu-latest runner but using a specially made Ubuntu 16 docker image (Dockerfile included).

Move to Ubuntu 16 docker image

---

Libs/Mesh/MeshWarper.cpp

No longer calling RemoveDeletedCells.  We don't seem to need it and it appears to be crashing sometimes (#1405)
Looking at the code and the crash, it appears to me that an array is
attempting to be copied from the old poly data to the new one, but
they have different numbers of points.

Fix crash #1405

---

Examples/Python/notebooks/tutorials/getting-started-with-data-augmentation.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-exploring-segmentations.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-meshes.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-notebooks.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-segmentations.ipynb
Examples/Python/notebooks/tutorials/getting-started-with-shape-cohort-generation.ipynb
Python/shapeworks/shapeworks/plot.py

This commit basically removes the interactive flag which was a misleading nomenclature and replaced it with a notebook flag in the pyvista plotters.
[A] When the notebook flag is False (this is the default now), it generates a render window and the visualization is performed in this window, you can close this window (tested on Linux) without affecting the rest of the code.
[B] When the notebook flag is True the rendering process is still done via OpenGL which requires an empty window that will pop open, but the visualization itself will be inline in the notebook:
This causes two problems and the suggestion is to never use this.
- Either you cannot close the window or if you close it then the notebook hangs
- Due to communication between the renderer and notebook the interactivity is very …

Notebook Visualization Fix

---

CMakeLists.txt

This should fix #1598.
This uses CMake to check the hash of one of the files tracked by git-lfs.  If a user/developer clone ShapeWorks without git-lfs, it will error out, rather than let them build and produce strange errors for `make test` and other things.
Now CMake will immediately bomb out with something like this:
CMake Error at CMakeLists.txt:16 (message):
MD5 hash of
'/home/user/shapeworks/Testing/data/icp_baseline.nrrd' is
incorrect.  This most likely means that git-lfs was not installed when
ShapeWorks was cloned.

Fix #1598 - CMake check for git-lfs

---

Applications/shapeworks/MeshCommands.cpp
Libs/Mesh/Mesh.cpp
Libs/Mesh/Mesh.h
Libs/Python/ShapeworksPython.cpp
Testing/MeshTests/MeshTests.cpp
Testing/PythonTests/PythonTests.cpp
Testing/PythonTests/meshwrite.py
Testing/shapeworksTests/meshwrite.sh
Testing/shapeworksTests/shapeworksTests.cpp

This PR addresses #1400. Mesh files can be saved as binary or ASCII files. The default option is ASCII. This change has been added to command-line, C++, and Python API. Unit tests have been added.

Adding option to save mesh file as binary (default is ascii)

---

Libs/Image/Image.cpp
Testing/ImageTests/ImageTests.cpp
Testing/PythonTests/crop.py

This PR resolves #1483.
Image.crop has been updated to use RegionOfInterestImageFilter instead of ExtractImageFilter.
Added tests.

Fix for #1483

---

Examples/Python/ellipsoid_evaluate.py
Libs/Particles/ShapeEvaluation.cpp

Address #1630 
After the warnings this is the output if the 3rd mode is queried for tiny test with 3 samples: 
```
(shapeworks_new) iyerkrithika@krithika:~/ShapeWorks_new/ShapeWorks/Examples/Python> python RunUseCase.py ellipsoid_evaluate --tiny_test
Using shapeworks module from /home/sci/iyerkrithika/ShapeWorks_new/ShapeWorks/Python/shapeworks/shapeworks/__init__.py
Using shapeworks from /home/sci/iyerkrithika/ShapeWorks_new/ShapeWorks/build/bin/shapeworks
Compactness
-----------
Invalid mode of variation specified
Compactness value of the 3rd mode -  0.0
Generalization
--------------
Invalid mode of variation specified
Generalization value of the 3rd mode -  0.0
Specificity
--------------
Invalid mode of variation specified
Specificity value of the 3rd mode -  0.0
````

Mode of variation check for shape evaluation

---

Python/ShapeCohortGenPackage/ShapeCohortGen/CohortGenUtils.py
docs/use-cases/stats-based/femur-pvalues.md

1. Added clarification based on a question asked on discourse: https://shapeworks.discourse.group/t/p-value-feature-map/70
2. ShapeCohortGenPackage was failing because of the way shapeworks was imported:
`from shapeworks import *`
This was causing the `range` function to misbehave and hence this error: 
Changed the import statement to: `import shapeworks as sw`, and now the package works without any error.

Small fix for cohort generator and added documentation

---

Libs/Optimize/ParticleSystem/ContourDomain.cpp
Libs/Optimize/ParticleSystem/ContourDomain.h
Libs/Optimize/ParticleSystem/itkParticleDomain.h
Libs/Optimize/ParticleSystem/itkParticleSystem.cxx

This PR fixes:
* #1689 
We now apply the per domain local inverse transforms to the shared split direction.  This fixes the reflection problem and should also improve splitting consistency any time that procrustes or input prefix transforms are used.

Fix #1689 - Particle splitting needs to use domain transforms

---

Libs/Mesh/MeshWarper.h
Libs/Python/ShapeworksPython.cpp

Allow to do the mesh warping in Python without calling external exe tool shapeworks.
Allow to retrieve the warping matrix and the cleaned reference model.

Add MeshWarper in Python bindings.

---

Libs/Mesh/Mesh.cpp
Libs/Mesh/Mesh.h
Testing/MeshTests/MeshTests.cpp

for copy ctors and assignment
also moves Mesh::read into independent class, protecting its undesired use by other Mesh functions
#1702

ensure Mesh invalidates locators when appropriate

---

Libs/Groom/Groom.cpp
Libs/Optimize/OptimizeParameters.cpp
Libs/Project/Project.cpp
Libs/Project/Project.h
Libs/Utils/StringUtils.cpp
Libs/Utils/StringUtils.h
Studio/src/Data/Shape.cpp
Studio/src/Groom/GroomTool.cpp
Studio/src/Visualization/Viewer.cpp

Address
* #1730 
* Fix non-thread-safe string utilities that can potentially cause incorrect/duplicate paths in grooming output
* Fix initial opacity in Studio viewer.

Address #1730

---

Applications/shapeworks/SharedCommandData.h
Libs/Common/Shapeworks.cpp
Libs/Common/Shapeworks.h
Libs/Image/Image.cpp
Libs/Image/Image.h
Libs/Image/VectorImage.cpp
Libs/Image/VectorImage.h
Libs/Mesh/Mesh.cpp
Libs/Mesh/Mesh.h
Libs/Particles/ReconstructSurface.cpp
Libs/Python/ShapeworksPython.cpp
Testing/ImageTests/ImageTests.cpp

Address Image::evaluate part of:
* #1080 
This adds Image::evaluate using a similar approach as was done for VectorImage with the advantage/difference that the interpolator is created only when first used.
Also cleaned up Mesh and Image classes a little bit.  There's a lot of formatting change for the most part.

Image::evaluate

---

Libs/Mesh/MeshWarper.cpp
Libs/Mesh/MeshWarper.h

Invert Key/Value since multiple landmarks can have the same reference vertex id.

Landmarks warping map amend

---

Python/shapeworks/shapeworks/utils.py
Studio/src/Python/PythonWorker.cpp
Studio/src/Python/PythonWorker.h
Studio/src/Resources/Info.plist.in
install_shapeworks.bat
install_shapeworks.sh

This PR fixes the python home and path issues for loading Studio.  Depending on the user's system, the wrong python home may get loaded and python will be unable to find the filesystem codec and unhelpfully calls "abort()" giving us no opportunity to even show and error message that python failed to load.

Fix python path and python home for Studio

---

Studio/src/Visualization/Viewer.cpp

Fixes:
* #1834 
This is a stop-gap fix until the new Project support is ready which
will better support different project configurations.

Fix #1834 - Studio crashes on XML multidomain

---

Libs/Particles/EvaluationUtil.h

The spec for std::normal_distribution allows for significant variation, which causes our specificity calculation to differ based on platform differences.  This PR switches to boost::normal_distribution to give us a consistent implementation across platforms.
Addresses:
* #1853

Fix #1853 by switching to boost normal_distribution that gives us a consistent implementation across platforms

---

devenv.sh

Print warning if not found, update usage.
no arguments given:
```
$ source devenv.sh
ERROR: must call this script using "source ./devenv.sh <BUILD/BIN_DIR>"
```
wrong path given:
```
$ source devenv.sh .
Source directory: /Users/amorris/sci/shapeworks/code
Binary directory: /Users/amorris/sci/shapeworks/code
Warning: shapeworks executable not present in /Users/amorris/sci/shapeworks/code
Did you specify the correct build/bin dir?
```
correct:
```
$ source devenv.sh ../build/bin
Source directory: /Users/amorris/sci/shapeworks/code
Binary directory: /Users/amorris/sci/shapeworks/build/bin
shapeworks executable found /Users/amorris/sci/shapeworks/build/bin
```

Update dev_env.sh script to check for presence of shapeworks executable

---

.github/workflows/build-windows.yml
Libs/Python/ShapeworksPython.cpp
Support/package.sh
Support/package_windows.sh
devenv.sh
docs/python/python-api.md
install_shapeworks.sh
mkdocs.yml

Adds Python API documentation to mkdocs site using [`mkdocstrings`](https://mkdocstrings.github.io/).
Addresses:
* #1864 
Adds two new pip dependencies, `mkdocstrings==0.19.0` and `mkdocstrings-python==0.7.1`.
Results can be seen with `mkdocs serve` after successful build.  Looks like this:

Add Python API documentation

---

build_dependencies.sh

Address #1905 by adding a check to make sure `source` isn't being used with build_dependencies.sh

---

Libs/Common/Logging.cpp
Libs/Common/Logging.h
Libs/Particles/ParticleShapeStatistics.cpp
Libs/Particles/ParticleShapeStatistics.h
Libs/Project/ProjectReader.cpp
Studio/src/Analysis/AnalysisTool.cpp
Studio/src/Analysis/AnalysisTool.h
Studio/src/Analysis/ShapeEvaluationJob.cpp
Studio/src/Data/Session.cpp
Studio/src/Interface/StatusBarWidget.cpp

This PR addresses:
* #1774 
It also adds a progress bar to project loading and asks the user if they really want to run the shape evaluation for large numbers of particles/shapes (any time the SVD is going to use more than about 4GB of memory).

Disable auto shape evaluation

---

Libs/Groom/Groom.cpp
Libs/Groom/Groom.h

Fix #1387 by keeping a list of used filenames within a grooming operation and add a number increment if there is a clash.

---

.github/workflows/Dockerfile
.github/workflows/build-linux.yml

Re-enable LD_LIBRARY_PATH, apparently linuxdeployqt can't find Qt despite conda being activated.
```
2022-11-03T02:31:04.1170164Z + linuxdeployqt ShapeWorksStudio -verbose=2
2022-11-03T02:31:04.1224745Z linuxdeployqt: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Re-enable LD_LIBRARY_PATH, apparently linuxdeployqt can't find Qt

---

install_shapeworks.sh

Fixes:
* #1933 
Array access was working for zsh for some reason, but not bash.

Fix #1933 - Conda environment

---

Libs/Analyze/Particles.cpp
Libs/Analyze/Particles.h
Libs/Analyze/Shape.cpp
Libs/Analyze/Shape.h
Libs/Common/Logging.h
Studio/src/CMakeLists.txt
Studio/src/Data/Preferences.cpp
Studio/src/Data/Preferences.h
Studio/src/Data/PreferencesWindow.cpp
Studio/src/Data/PreferencesWindow.ui
Studio/src/Interface/ShapeWorksStudioApp.cpp
Studio/src/Interface/ShapeWorksStudioApp.h
Studio/src/Visualization/Lightbox.cpp
Studio/src/Visualization/ParticleColors.cpp
Studio/src/Visualization/ParticleColors.h
Studio/src/Visualization/Viewer.cpp
Studio/src/Visualization/Viewer.h
Studio/src/Visualization/Visualizer.cpp
Studio/src/Visualization/Visualizer.h

Resolves:
* #1773 
* #1930 
Particle display can now be controlled per-domain, similar to the surface opacity.
Additionally, a new coloring method solves #1930.  The old mode is also provided as a preference:
Original:
Distinct:

Per domain particle display control and alternate color support

---

Libs/Analyze/Particles.cpp
Libs/Analyze/Particles.h
Libs/Analyze/Shape.cpp
Libs/Analyze/Shape.h
Libs/Common/Logging.h
Libs/Project/ExcelProjectReader.cpp
Libs/Project/ExcelProjectWriter.cpp
Libs/Project/ExcelProjectWriter.h
Libs/Project/JsonProjectWriter.cpp
Libs/Project/Project.cpp
Libs/Project/ProjectReader.cpp
Libs/Project/ProjectUtils.cpp
Studio/src/Analysis/AnalysisTool.cpp

Resolves:
* #1775 
The problem was that the procrustes transforms were being applied for each domain independently and always, regardless of which alignment domain was set.  Only the procrustes transform of the alignment domain should be used, or none for global/local.  If the user has performed no alignment in grooming, then local and global will be the same.  That is, until we provide a global procrustes.

1775 procrustes

---

Libs/Optimize/ContourDomain.cpp

* #1947 
Not certain this fixes #1947, but plausibly does so.
Works around a bug in VTK where the array allocated in vtkDijkstraGraphGeodesicPath::GetCumulativeWeights using `new` is incorrectly cleaned up using `free` (undefined behavior).
Valgrind reports this as:
Mismatched free() / delete / delete []

Hopefully fix #1947

---

Libs/Analyze/MeshGenerator.cpp
Libs/Mesh/MeshWarper.cpp

Fixes:
* #1998 
Return an empty mesh on warp mesh error instead of nullptr.
Improve error reporting of mesh warp errors.

Fix 1998 crash

---

Support/package_windows.sh
Support/shapeworks.nsi

Fixes #2014 
* #2014 
A change in the runner environment has caused a different python DLL to be loaded when going to build the docs.  This happens due to some fixup that we have to do for PYTHONPATH for a dependency of mkdocs (libgaffe?).  On windows, it cannot parse the colons to search for modules, so we change to semicolons, but this changes how python is finding it's DLL and it's breaking.
There is probably some way around this, but it's extremely time consuming to maintain the offline docs for the windows build.  There isn't really any need for it now that we have the versioned mkdocs on the website.  As discussed the last time we invested time into this, we would drop it the next time it caused a problem.

Fix #2014 - Windows GitHub Actions build

---

.github/workflows/build-linux.yml

WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: pip cache commands can not function since cache is disabled.

Remove pip cache clear.  Getting this error:

---

Libs/Project/Parameters.cpp
Libs/Project/Parameters.h
Libs/Project/Variant.cpp
Libs/Project/Variant.h
Libs/Python/ShapeworksPython.cpp
Testing/data/python/project/project.py

Allows to retrieve optimization parameters from xlsx project:
import shapeworks as sw
p = sw.Project()
p.load("sample.xlsx")
optim_params = p.get_parameters("optimize").as_map()
Notes: the old Parameters:get_map() and set_map() were not usable (because tsl::ordered_map not supported by pybind11), replaced by as_map()
Added Variant.as_str() for access in Python.

Retrieve Project Parameters using Python binding.

---

docs/getting-started/interfaces.md

Adds ShapeWorks Cloud to the interfaces list instead of the list saying "Work In Progress"

Update interfaces to show ShapeWorks Cloud

---

Examples/Python/Data/Verification.zip
Examples/Python/thin_cavity_bean.py
Libs/Optimize/Domain/VtkMeshWrapper.cpp
Testing/MeshTests/MeshTests.cpp
Testing/PythonTests/geodesic.py
Testing/data/geodesic.txt
Testing/data/geodesic1.vtk
Testing/data/geodesic3.vtk
Testing/data/geodesic_curve.vtk
Testing/data/geodesic_curve_py.vtk

https://geometry-central.net/surface/algorithms/geodesic_distance/
useRobustLaplacian is true, the solver will internally use a robust intrinsic Laplacian, including mollification & tufting for nonmanifold inputs. See “A Laplacian for Nonmanifold Triangle Meshes” [Sharp & Crane 2020 @ SGP] for algorithmic details and citation.

Enable useRobustLaplacian to heat solver

---

Libs/Analyze/Analyze.cpp
Libs/Analyze/Analyze.h
Studio/Analysis/AnalysisTool.h

This PR fixes the alignment reference domain in the offline analysis.  Previously, the computed shapes would overlap:
Now we use the global alignment:
This PR also fixes the output location of the mean shape and particles (source vs target)

Global reference domain for offline analysis

---

Libs/Mesh/Mesh.cpp
Libs/Python/ShapeworksPython.cpp
Testing/MeshTests/MeshTests.cpp

return (bary * values.transpose()).mean(); is the mean of the OUTER product so the values returned by interpolateFieldAtPoint() are wrong.
We could use (values.transpose()*bary)(0) but it is more clear using: values[0] * bary[0] + values[1] * bary[1] + values[2] * bary[2]; for the interpolation

Bug fix Mesh::interpolateFieldAtPoint() and add Python binding.

---

Libs/Analyze/StudioMesh.cpp
Libs/Particles/ParticleSystemEvaluation.cpp
Libs/Particles/ParticleSystemEvaluation.h
Libs/Particles/ShapeEvaluation.cpp
Libs/Particles/ShapeEvaluation.h
Studio/Analysis/AnalysisTool.cpp
Studio/Analysis/AnalysisTool.h
Studio/Analysis/AnalysisTool.ui
Studio/Analysis/ShapeEvaluationJob.cpp
Studio/Analysis/ShapeEvaluationJob.h
Studio/Data/Session.cpp
Studio/Data/Session.h
Studio/Interface/ShapeWorksStudioApp.cpp
Studio/Interface/ShapeWorksStudioApp.h

This PR addresses part of #2218, adding the ability to show predicted scalars for samples and the difference to the true scalars.

#2218 scalar evaluation

---

Studio/Visualization/Visualizer.cpp

Fix #2219 - Screenshot with transparent background shows transparent particles

---

.github/workflows/gha_conda.sh
install_shapeworks.bat
install_shapeworks.sh
python_requirements.txt

This should hopefully resolve a lot of problems more easily install the CUDA version of pytorch on supporting systems.

Resolve #2224 - Switch to light-the-torch for pytorch installation.

---

Examples/Python/deep_ssm.py
Python/DeepSSMUtilsPackage/DeepSSMUtils/run_utils.py
Python/DeepSSMUtilsPackage/DeepSSMUtils/train_viz.py

Fixes for #2232
Fix error:
e)
celery-gpu-1  |   File "/opt/conda/envs/shapeworks/lib/python3.9/site-packages/DeepSSMUtils/run_utils.py", line 503, in process_test_predictions
celery-gpu-1  |     reference_index = DeepSSMUtils.get_reference_index(project)
celery-gpu-1  | AttributeError: module 'DeepSSMUtils' has no attribute 'get_reference_index'~
Also add the code to run this as part of the tiny test.

Fixes for #2230

---

Libs/Project/ProjectReader.cpp
Studio/Data/DataTool.cpp

* #2251 
Fixed bug where column numbers were used for name and notes.  When excluded/fixed are present, they were being used as the notes mistakenly.

2251 - Fix notes column

---

Libs/Particles/ParticleShapeStatistics.cpp
Libs/Particles/ParticleShapeStatistics.h
Libs/Particles/ParticleSystemEvaluation.cpp
Libs/Particles/ParticleSystemEvaluation.h
Libs/Particles/ShapeEvaluation.cpp
Libs/Particles/ShapeEvaluation.h
Libs/Python/ShapeworksPython.cpp
Studio/Analysis/AnalysisTool.cpp
Studio/Analysis/AnalysisTool.h
Studio/Analysis/AnalysisTool.ui
Studio/Analysis/ShapeEvaluationJob.cpp
Studio/Analysis/ShapeEvaluationJob.h
Studio/Data/Session.h
Studio/Data/Worker.cpp
Studio/Data/Worker.h
Studio/Utils/AnalysisUtils.cpp

* #2212 
This PR adds the ability to use particle to surface rather than particle to particle for generalization and specificity computation.  
* Specificity in particular can be quite slow, so it's parallelized across subjects.
* Specificity and Generalization jobs can now be aborted.  When switching between particle and surface distance, the other jobs are stopped.  Also stopped on shutdown for clean exit.

New generalization and specificity

---

Studio/Analysis/AnalysisTool.cpp

The alignment setting can in some cases lag behind, meaning that as you change the dropdown, you get the previous setting.

Fix alignment setting.

---

Studio/Analysis/AnalysisTool.cpp
Studio/Analysis/AnalysisTool.h
Studio/Data/Session.cpp
Studio/Data/Session.h
Studio/Interface/ShapeWorksStudioApp.cpp
Studio/Visualization/Lightbox.cpp
Studio/Visualization/SliceView.cpp
Studio/Visualization/SliceView.h
Studio/Visualization/Viewer.cpp
Studio/Visualization/Viewer.h
Studio/Visualization/Visualizer.cpp

* #2321
* Add ability to show shape intersection with multiple domains.
* Fix display of non-feature contour
* Fix bug where transform is mistakenly inverted with slice change
* Fixing display of contours without feature maps.
* Fixing colormap issues.  No longer resetting view when changing uniform on/off
* Fixing colormap for contour slice view
* Adding ability to show colormap on slice contour. (#2321)
* Fix scalar bar text positioning changing by changing order of actor adding.  Not sure why this fixes it or what the original problem was.
* Reduce the number of places where the number of viewers gets reset as it is really annoying when yo
u are on a single viewer and change a setting and it goes back to 4x4.

Studio analysis updates

---

Studio/Data/DataTool.cpp
Studio/Data/LandmarkTableModel.cpp
Studio/Data/Preferences.cpp
Studio/Data/Preferences.h
Studio/Data/Session.cpp
Studio/Data/Session.h
Studio/Groom/GroomTool.cpp
Studio/Groom/GroomTool.h
Studio/Interface/ShapeWorksStudioApp.cpp
Studio/Interface/ShapeWorksStudioApp.h
Studio/Optimize/OptimizeTool.cpp
Studio/Visualization/Viewer.cpp

Project modification tracking

---

Libs/Analyze/MeshGenerator.cpp
Libs/Analyze/Shape.cpp
Libs/Analyze/Shape.h
Libs/Image/Image.cpp
Libs/Image/Image.h
Libs/Image/ImageUtils.cpp
Libs/Image/ImageUtils.h
Libs/Optimize/Optimize.cpp
Studio/CMakeLists.txt
Studio/Data/DataTool.cpp
Studio/Data/DataTool.h
Studio/Data/SegmentationToolPanel.cpp
Studio/Data/SegmentationToolPanel.h
Studio/Data/SegmentationToolPanel.ui
Studio/Data/Session.cpp
Studio/Data/Session.h
Studio/Utils/StudioUtils.cpp
Studio/Visualization/Lightbox.cpp
Studio/Visualization/PaintWidget.cpp
Studio/Visualization/PaintWidget.h
Studio/Visualization/SliceView.cpp
Studio/Visualization/SliceView.h
Studio/Visualization/Viewer.cpp
Studio/Visualization/Viewer.h
Studio/Visualization/Visualizer.cpp
Studio/Visualization/Visualizer.h

* #2286
This PR adds a rudimentary segmentation tool with the ability to mark the segmentation as well as an include/exclude label for use with MonaiLabel/etc.

Segmentation Tool

---

.github/workflows/build-mac.yml
.github/workflows/gha_deps.sh

* #2341 
Attempting to use older SDK and target no longer works on macos-13 runner.
Disabling this for now and just targeting MacOS 13.

2341 - Fix mac/intel runner 

---

ExternalLibs/robin_hood/robin_hood.h
Libs/Analyze/Analyze.cpp
Libs/Analyze/Shape.cpp
Libs/Analyze/Shape.h
Libs/Mesh/Mesh.cpp
Libs/Mesh/Mesh.h
Libs/Mesh/MeshUtils.cpp
Libs/Mesh/MeshUtils.h
Libs/Optimize/Domain/MeshDomain.cpp
Libs/Optimize/Domain/MeshDomain.h
Libs/Optimize/Domain/MeshWrapper.cpp
Libs/Optimize/Domain/MeshWrapper.h
Libs/Optimize/Domain/Surface.cpp
Libs/Optimize/Domain/Surface.h
Libs/Optimize/Neighborhood/ParticleNeighborhood.cpp
Libs/Optimize/Optimize.cpp
Libs/Optimize/OptimizeParameterFile.cpp
Libs/Optimize/Sampler.cpp
Libs/Optimize/Sampler.h
Libs/Particles/ParticleNormalEvaluation.cpp
Libs/Particles/ParticleNormalEvaluation.h
Studio/Job/ParticleNormalEvaluationJob.cpp
Testing/OptimizeTests/OptimizeTests.cpp
Testing/ParticlesTests/ParticlesTests.cpp

* #2349 
This PR reduces the per triangle memory usage of mesh domains significantly.
It also generates gradient normals on demand, so if they are not needed, they are not computed, saving further memory and computation time.

2349 - Improve mesh domain memory usage

---

Examples/Python/ellipsoid_multiple_domain_mesh.py
Libs/Groom/Groom.cpp
Libs/Particles/ParticleShapeStatistics.cpp

* #2360 
This PR fixes the ellipsoid_multiple_domain_mesh example.
It also fixes MLPCA when using anything other than just X,Y,Z.

2360 - Fix ellipsoid_multiple_domain_mesh example not working Use Case

---

Libs/Analyze/Shape.cpp
Studio/CMakeLists.txt
Studio/Data/SegmentationToolPanel.cpp
Studio/Visualization/PaintWidget.cpp
Studio/Visualization/SliceView.cpp
Studio/Visualization/StudioImageActorPointPlacer.cpp
Studio/Visualization/StudioImageActorPointPlacer.h
Studio/Visualization/Viewer.cpp
Studio/Visualization/Viewer.h

* #2356 
Hide include/exclude for 6.6 release (#2356)
"included" part of segmentation should become part of the object
Fix bug where segmentation tool does not operate on the correct location.  vtkImageActorPointPlacer does not take into account the UserTransform.  I had to subclass it as StudioImageActorPointPlacer.

2356 - Segmentation Tool Updates

---

python_requirements.txt

* #2365 
Needed typing_extensions==4.12.2

Fix #2365 - Python dependency version problem

---

Libs/Groom/Groom.cpp
Studio/DeepSSM/DeepSSMJob.cpp
Studio/DeepSSM/DeepSSMTool.cpp
Studio/DeepSSM/DeepSSMTool.ui

* #2398
We now have the user set training and val and test is auto set.
Also fix crash and add error messages.

Fix #2398 - Crash on DeepSSM "Groom Training Shapes" when training is set to 0%

---

Applications/shapeworks/Commands.cpp
Applications/shapeworks/shapeworks.cpp
Libs/Common/CMakeLists.txt
Libs/Common/Logging.cpp
Libs/Common/Profiling.cpp
Libs/Common/Profiling.h
Libs/Optimize/Function/CorrespondenceFunction.cpp
Libs/Optimize/GradientDescentOptimizer.cpp
Libs/Optimize/Optimize.cpp
Libs/Project/Project.cpp
Libs/Utils/CMakeLists.txt
Libs/Utils/PlatformUtils.h
Python/shapeworks/shapeworks/shape_scalars.py
Studio/Analysis/AnalysisTool.cpp
Studio/Data/Session.cpp
Studio/Job/ShapeScalarJob.cpp
Studio/Job/ShapeScalarJob.h

* Add basic profiling and tracing infrastructure
* Speed improvements for correspondence function of optimizer
This PR adds a very basic profile and trace capability to ShapeWorks.  It is controlled with environment variables SW_TIME_PROFILE=1 and SW_TIME_TRACE=1.  When profiling is on, a file, `profile.txt` is written at the end of execution and displayed on the screen as well.  It looks roughly like this:
```
THREAD 0:
------------------------------------------------------------------------------------------------------
%Time    Exclusive    Inclusive   #Calls   #Child    Exclusive    Inclusive Name
total ms     total ms                        ms/call      ms/call
------------------------------------------------------------------------------------------------------
100.0           96 …
```

Add profiling/tracing module and speed improvments to correspondence function of optimizer

---

Libs/Analyze/Shape.cpp
Libs/Common/Logging.cpp
Libs/Common/Logging.h
Libs/Groom/Groom.cpp
Libs/Groom/Groom.h
Libs/Groom/GroomParameters.cpp
Libs/Groom/GroomParameters.h
Libs/Mesh/MeshUtils.cpp
Libs/Mesh/MeshUtils.h
Libs/Mesh/MeshWarper.cpp
Libs/Mesh/MeshWarper.h
Libs/Optimize/Domain/DomainType.h
Libs/Project/Project.cpp
Libs/Project/Project.h
Libs/Project/ProjectUtils.cpp
Libs/Python/ShapeworksPython.cpp
Libs/Utils/Utils.cpp
Libs/Utils/Utils.h
Studio/Groom/GroomTool.cpp
Studio/Groom/GroomTool.h
Studio/Groom/GroomTool.ui
Studio/Interface/ShapeWorksStudioApp.cpp
Studio/Utils/StudioUtils.cpp
Studio/Utils/StudioUtils.h
Studio/Visualization/PlaneWidget.cpp
Studio/Visualization/Viewer.cpp
Testing/MeshTests/MeshTests.cpp

* #2397
Add support for multiple shared boundaries:

Add support for multiple shared boundaries

---

.github/workflows/build-linux-debug.yml
.github/workflows/build-linux.yml
.github/workflows/build-mac-arm64.yml
.github/workflows/build-mac.yml
.github/workflows/build-windows.yml
Libs/Groom/Groom.cpp
Libs/Groom/Groom.h
Libs/Image/Image.cpp
Libs/Image/Image.h
Libs/Image/ImageUtils.cpp
Libs/Image/ImageUtils.h
Libs/Python/ShapeworksPython.cpp

* #2430 
~~Add Python API for  Image.toAxisAligned()~~
I've changed this now.  Since we are already changing orientation to RAI on image load, we may as well add this to image load instead of having a command/python API, etc.  This greatly simplifies things and makes it more robust.

Ensure images are axis aligned when loading

---

Libs/Groom/Groom.cpp

Fix #2428 - Groom: Fixed domains should not clear transforms on grooming

---

Libs/Particles/ParticleShapeStatistics.cpp
Libs/Particles/ParticleShapeStatistics.h
Libs/Python/ShapeworksPython.cpp

* #2425
This PR adds additional functionality to support using ShapeWorks PCA from Python.
Example script:
```python
import shapeworks as sw
import glob
import os
import sys
import numpy as np
def read_data():
script_dir = os.path.dirname(os.path.abspath(__file__))
particleFilesDir = script_dir + "/data/la_particles/"
particleFilesList = glob.glob(particleFilesDir + "*world.particles")
print(particleFilesList)
ps = sw.ParticleSystem(particleFilesList)
return ps
new_sample = np.loadtxt(os.path.dirname(os.path.abspath(__file__)) +
"/data/la_particles/CARMA0046_groomed_world.particles")
new_sample = new_sample.flatten()
project = sw.Project()
os.chdir("data")
project.load("la.xlsx")
pca = sw.ParticleShapeStatistics()
pca.PCA(project)
mean_shape = pca.getMean()
print("Mean shape: ", …
```

Python PCA API
