src/ITKParticleSystem/itkMaximumEntropyCorrespondenceSampler.h, src/ITKParticleSystem/itkParticleDualVectorFunction.h
=> moved the relative weighting to weight the sampling part of the objective function 

Post/source/ShapeWorksPost-V1/examples/Ellipsoid/ellipsoid.xml
Please delete branch after merge.
=> Removed hard coded paths so that the POST example can be run anywhere, by anyone

CMakeLists.txt
=> Fix #159 - library path

Studio/src/Application/Data/MeshGenerator.cc, Studio/src/Application/Data/Project.cc, Studio/src/Application/Data/Project.h, Studio/src/Application/Visualization/ShapeWorksStudioApp.cc, Studio/src/Application/main.cc
Initial version of Studio light mode.
Replace Qt XML reader with TinyXML.
Support for old/current Studio file format as well as new View2 file format.
=> Studio Light Initial

Libs/ITKParticleSystem/itkParticleConstrainedModifiedCotangentEntropyGradientFunction.h
Shireen, try this and I hope it will build for you now.
=> Remove unneeded Utils.h

UseCaseDocumentation/LAMain.py, UseCaseDocumentation/OptimizeUtils.py, UseCaseDocumentation/ellipsoidMain.py
The LAMain is changed to be consistence with ellipsoid example and also the ellipsoid optimization parameters are changed.
=> Use case la

CMake/External-VTK.cmake, CMakeLists.txt
Praful, can you try this branch?
=> Fix #272 - Fix non-Qt build.

conda_installs.sh
This will ensure old versions will still work instead of making it a guessing game to get the correct (old) versions of the prerequisites.
(didn't modify .bat version since I don't have Windows handy to check availability of versions)
=> added versions to all the prerequisites installed by conda_installs.sh

Studio/src/Application/Visualization/Visualizer.cc
=> Only allow centering when on original meshes.

.github/workflows/build-mac.yml, Examples/Python/LAMain.py, Examples/Python/ellipsoidMain.py, Mac_README.txt, package.sh
This PR modifies the Mac build to create both a zip file and a pkg installer.  A new README describes how to use the pkg installed version.
I tested both methods on my machine, but it would be great if anyone else could as well.
=> Mac installer

Libs/Mesh/PreviewMeshQC/FEAreaCoverage.cpp, Libs/Mesh/PreviewMeshQC/FEAreaCoverage.h, Libs/Mesh/PreviewMeshQC/Intersect.cpp, Libs/Mesh/PreviewMeshQC/Intersect.h, Libs/Mesh/PreviewMeshQC/math3d.cpp, Libs/Mesh/PreviewMeshQC/math3d.h
Integrated PreviewMeshQC changes for coverage calculation
=> PreviewMeshQC changes for coverage calculation

Studio/src/Application/Visualization/ShapeWorksStudioApp.cc
=> Fix issue #312 - Studio cancel button not working.

Studio/src/Application/Visualization/Viewer.cc, Studio/src/Application/Visualization/Viewer.h
=> Add scalar bar to group difference display.

Examples/Python/AnalyzeUtils.py, Examples/Python/CommonUtils.py, Examples/Python/GroomUtils.py, Examples/Python/RunUseCase.py, Examples/Python/ellipse.py, Examples/Python/femur.py, Examples/Python/left_atrium.py, conda_installs.sh
I have added a function to CommonUtils , which takes the input files and runs k-mean clustering, then picks one sample from each cluster as the sub-sample data, by this approach we will get roughly the same set of samples for different runs.
=> La changes

Libs/Particles/itkParticleShapeStatistics.cpp
I mistakenly pushed a change I made while testing something out. This reverts that change.
=> Revert changes made in itkParticleShapeStatistics

conda_installs.sh
This will require write permission and on Mac Package and Windows, this folder will not be writable.
=> We should not be asking for an "editable" (-e) install of datasetutils

conda_installs.sh
Fix conditionals for zsh.  Still works with bash.
=> Fix conda_installs.sh for zsh (default on Mac Catalina)

Documentation/install/Windows_README.txt
Update Windows instructions regarding non-standard install location
=> Need python, not python3 for windows anaconda.

build_dependencies.sh
This fixes the ITK build when conda is activated with the other VTK.
=> Fix specification of VTK for building ITK.

Examples/Python/ellipsoid_fd.py
Fix some directory pathing updates I missed in #404
=> Fix directory paths for ellipsoid_fd

Libs/Optimize/Optimize.cpp
Fixes #416
This should fix the problem you were having with elllipse_fd
=> Fix "fixed domain" flag initialization.

.gitignore, BUILD.md, BUILD_Windows.md, conda_installs.bat
Added separate BUILD_Windows.md file with instructions for building from source specific to windows.
=> Separate windows build instructions

.github/workflows/build-linux.yml, Libs/Particles/CMakeLists.txt
Thanks @riddhishb for pointing out.
=> Fix Analyze -> Particles in CMakeLists.txt

Libs/Optimize/ParticleSystem/itkParticleMeshBasedGeneralEntropyGradientFunction.h
=> Fix memory leak

CMakeLists.txt
Seeing if ShapeWorks will build with C++17 on all the GitHub action platforms.
=> Set C++ standard to C++14

Documentation/Datasets.md, Python/DatasetUtilsPackage/DatasetUtils/GirderConnector.py, Python/DatasetUtilsPackage/DatasetUtils/__init__.py
See [Documentation/Datasets.md](https://github.com/SCIInstitute/ShapeWorks/blob/download_by_name/Documentation/Datasets.md) for usage info for the new function: downloadDatasetFiles.
=> Data Portal download list of files from dataset

conda_installs.sh
Trying to fix windows build on GitHub Actions
=> Use "python -m pip install --upgrade pip"

Documentation/Datasets.md, Python/DatasetUtilsPackage/DatasetUtils/GirderConnector.py, Python/DatasetUtilsPackage/DatasetUtils/__init__.py
Per Shireen's suggestion, combined `downloadDatasetFiles` and  `downloadDataset` so that there is only one user facing download function.
=> Combine downloadDatasetFiles into the downloadDataset function

Documentation/Datasets.md
Added info on the normalized folder names.
Better view of the new md file here: [https://github.com/SCIInstitute/ShapeWorks/blob/update_use_case_doc/Documentation/Datasets.md](https://github.com/SCIInstitute/ShapeWorks/blob/update_use_case_doc/Documentation/Datasets.md)
=> Update Datasets docs with new folder structure

Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
=> Remove m_NarrowBand from ParticleImageDomain

Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
=> Remove unnecessary doc

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml, README.md
This PR adds automatic deployment of changes to master to latest-mac, latest-windows, and latest-linux GH releases.  The release is overwritten each time.
=> Automatic deployment of master branch changes

BUILD.md, BUILD_Windows.md
using the shapeworks-dev-support email
=> add contact support instructions to top of BUILD and BUILD_Windows

Libs/Project/Parameters.h, Libs/Project/Project.cpp, Libs/Project/Project.h, Studio/src/Application/Data/Session.cpp, Studio/src/Application/Data/Session.h, Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp
This addresses the remaining item in #506
=> Add warning about spreadsheet projects saved in newer versions of ShapeWorks

Support/package_windows.sh
=> Remove *Test.exe from windows binary release package.

ChangeLog, Examples/Python/ellipsoid.py, Examples/Python/femur.py, Examples/Python/left_atrium.py
the changelog is updated and some inline link to documentations for the use cases.
=> Fix la memory

Libs/Project/Project.cpp
This fixes a crash where new data is added to an initial blank project in studio.
=> Fix crash where blank studio project has initial data added.

Testing/ImageTests/ImageTests.cpp, Testing/data/isoresample/image-anisotropic-input.nrrd, Testing/data/isoresample/image-anisotropic-isoresampled.nrrd
400MB down to 64K
22MB down to 22K
=> Resolve #428 by reducing the size of the test data.

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml
Fixes typo in marvinpinto/action-automatic-releases@1.0.0
=> Switch to marvinpinto/action-automatic-releases@latest

docs/dev/gh-actions.md
=> Add docs about GitHub Actions.

Python/DatasetUtilsPackage/DatasetUtils/GirderConnector.py, Python/DatasetUtilsPackage/DatasetUtils/__init__.py, docs/dev/datasets.md
Add API to get file list of a dataset
=> Add getFileList api to DatasetUtils

Examples/Python/RunUseCase.py, Studio/src/Application/Data/Session.cpp
This PR re-enables the ellipsoid_mesh use case and fix Studio for the output.
=> Fix ellipsoid mesh

Examples/Python/OptimizeUtils.py, Examples/Python/ellipsoid.py, Examples/Python/ellipsoid_fd.py, Examples/Python/ellipsoid_mesh.py, Examples/Python/femur.py, Examples/Python/femur_mesh.py, Examples/Python/left_atrium.py, Examples/Python/lumps.py, Libs/Optimize/Optimize.cpp
Update the optimize defaults per #745
=> Optimize defaults

Libs/Mesh/ComputeMeshGeodesics.cxx, Libs/Mesh/PreviewMeshQC/FEFillHole.cpp, Libs/Mesh/PreviewMeshQC/FEMesh.cpp, Libs/Mesh/PreviewMeshQC/math3d.h, Libs/Mesh/meshFIM.h, Libs/Particles/ParticleShapeStatistics.h, Studio/src/Application/Data/Shape.cpp, Studio/src/Application/Interface/SplashScreen.ui, Studio/src/Application/Optimize/OptimizeTool.cpp, Studio/src/Application/Visualization/Lightbox.cpp, Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp, Studio/src/Application/Visualization/ShapeWorksStudioApp.h, Studio/src/Application/Visualization/Visualizer.cpp, Studio/src/Application/main.cpp, Studio/src/Groom/ShapeWorksGroom.cpp, Studio/src/Groom/ShapeWorksGroom.h
* Fix #755 - Studio: newly imported shapes are missing filename corner annotations 
* Improve display on high-dpi windows devices (qt attribute change)
* Enable save to be save-as on new projects
* Adjust splash screen layout.  Equal size buttons.
=> Studio tweaks

Examples/Python/ellipsoid.py, Examples/Python/ellipsoid_cut.py, Examples/Python/femur.py, Examples/Python/femur_cut.py, Examples/Python/left_atrium.py
Fixies paths for use cases when --start_with_prepped_data is used
Fixes output paths of femur_cut use case
=> Use case path fix

.gitattributes
=> Move zips to LFS as they keep changing and accumulating storage in the history

Libs/Analyze/Reconstruction.cpp, Libs/Analyze/Reconstruction.h, Studio/src/Application/Data/Shape.cpp, Studio/src/Application/Data/SurfaceReconstructor.cpp, Studio/src/Application/Optimize/OptimizeTool.ui, Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp, Studio/src/Application/Visualization/ShapeWorksStudioApp.h, Studio/src/Application/Visualization/ShapeWorksStudioApp.ui
This PR resolves:
#791 - Studio: reset camera on centering change and after grooming with centering
#793 - Studio: Ability to set to two viewers 
#794 - Studio: Allow relative weighting up to 1000
#770 - Studio/Reconstruction - Relax same size constraint on distance transforms
=> Studio updates

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml
Trying to fix the GitHub Action conda problem.
=> Update to conda-incubator/setup-miniconda@v2.0.0

Studio/src/Application/Data/Session.cpp, Studio/src/Application/main.cpp
This PR changes Studio to allow input files to be supplied on the command line. e.g.
ShapeWorksStudio *.nrrd
=> Load input files on command line

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml
The install qt action started failing.  Trying a new version.
=> Trying qt install action 2.11.1

Examples/Python/GroomUtils.py
=> Add missing printCmd arguement

Libs/Mesh/Mesh.cpp, Libs/Mesh/PreviewMeshQC/FEAreaCoverage.cpp, Libs/Mesh/PreviewMeshQC/FEAreaCoverage.h
=> Fix leak in Mesh::coverage by using smart pointers

conda_installs.sh
Adding support for cuda 11.1 and 11.2
=> Pytorch install

.github/workflows/build-windows.yml, Studio/src/Application/CMakeLists.txt
This addresses #615.
More complicated than I would have liked, but a symlink doesn't work and you can't directly write an executable file using CMake, so it has to write elsewhere and copy.
=> Address #615 by creating a script to run ShapeWorksStudio from bin

Examples/Python/femur.py, Examples/Python/femur_cut.py, Examples/Python/left_atrium.py
Fixes so that femur, femur_cut, and left_atrium work for release 6.0
=> Fix use cases for Release 6.0

Examples/Python/CommonUtils.py
Now the path regex accounts for "/" and \\\
=> Fixed path regex search in datasubset download

Examples/Python/notebooks/tutorials/getting-started-with-meshes.ipynb
=> Changing ellipsoid-v2 to ellipsoid-v1

Libs/Optimize/ParticleSystem/itkParticleImplicitSurfaceDomain.txx
#1084 fixed
This should not affect anything other than ellipsoid_cut.
=> Fixed getting stuck issue

Studio/src/Application/Data/Session.cpp, Studio/src/Application/Groom/GroomTool.cpp, Studio/src/Application/Visualization/ShapeWorksWorker.cpp
=> Studio handle read only

Examples/Python/femur.py, Examples/Python/femur_cut.py
=> Moving interactive step to very beginning of femur and femur_cut use cases

Examples/Python/data_augmentation.py, Examples/Python/deep_ssm.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/Analyze.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/TorchLoaders.py
=> Deep ssm fix2

Libs/Optimize/Optimize.cpp
Use mean energy when the number of domains is 1.
=> Fix #1138 single image domain

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml, build_dependencies.sh
This should resolve #1152
See: https://www.shellscript.sh/tips/pipestatus/
=> Fix build_dependencies.sh return code

Examples/Python/notebooks/tutorials/getting-started-with-data-augmentation.ipynb
=> Update getting-started-with-data-augmentation.ipynb with the newer shapeworks env setup.

Studio/src/Application/Visualization/BarGraph.cpp, Studio/src/Application/Visualization/BarGraph.h
=> Dynamically adjust font size and layout for bar chart.

Libs/Optimize/ParticleSystem/itkParticleProcrustesRegistration.cxx, Libs/Optimize/ParticleSystem/itkParticleSystem.h
This fixes #1225.
After this change:
https://user-images.githubusercontent.com/1693349/116474590-f01b8300-a835-11eb-9129-10b701221b25.mp4
=> Change procrustes to use positions after prefix transform.

Libs/Mesh/MeshWarper.cpp, Libs/Mesh/MeshWarper.h, Studio/src/Application/Analysis/AnalysisTool.cpp, Studio/src/Application/CMakeLists.txt, Studio/src/Application/Data/MeshGenerator.h, Studio/src/Application/Data/MeshManager.cpp, Studio/src/Application/Data/MeshManager.h, Studio/src/Application/Data/QMeshWarper.cpp, Studio/src/Application/Data/QMeshWarper.h, Studio/src/Application/Visualization/ShapeWorksStudioApp.cpp
This PR addresses #1229 by adding a progressbar for mesh warping.
=> Studio mesh warp progress

Libs/Optimize/Optimize.cpp
@medakk's suggestion worked.  I tested before and after the fix and confirmed.
=> Fix #846 - <use_shape_statistics_after> particle count.

Studio/src/Application/Visualization/Viewer.cpp, Studio/src/Application/Visualization/Visualizer.cpp, Studio/src/Application/Visualization/Visualizer.h
This PR addresses #1288.
Mesh attempted to be exported:
Mesh exported before this PR:
After this PR:
=> Address #1288 by transforming and appending domains

Examples/Python/femur.py, Examples/Python/femur_cut.py, Testing/UseCaseTests/UseCaseTests.cpp
This should fix #1292 
It also adds an automated test for "femur --groom_images --tiny_test" that would have been failing before this fix.
=> Fix femur use cases

Support/osxscripts/preinstall, Support/package.sh, conda_installs.sh
* Don't call nbstripout --install --attributes .gitattributes if git is not installed.
* Add missing update_installed_python_module_binary_path.py to package
* Fix deletion /Application/ShapeWorks -> /Applications/ShapeWorks
#1297
#1296
=> Fix Install stuff

conda_installs.bat, install_python_module.bat, update_installed_python_module_binary_path.py
Working with Krithika we verified this works on Windows, and that the minor modifications to conda_installs.bat also work.
=> Fix python install on windows

Examples/Python/femur_cut.py, Studio/src/Application/Groom/GroomTool.cpp
=> Add groom skip question

Examples/Python/ellipsoid_evaluate.py, Examples/Python/ellipsoid_pca.py, Python/shapeworks/shapeworks/plot.py
=> Moving plots to pymodule plot function

Support/package.sh
Hopefully fixes #1345 
Also reduce the size of the mac/linux deployments since we have no reason to ship any static libraries.
=> Fix mac app

Studio/src/Data/Session.cpp, Studio/src/Data/StudioMesh.cpp
Fixes issue #1390, there was an integer data type being used that should have been float.
Also fixes read-only being marked on some projects that shouldn't.
=> Fix feature quantization (issue #1390)

Examples/Python/RunUseCase.py, Examples/Python/femur_pvalues.py, Python/shapeworks/shapeworks/__init__.py, Python/shapeworks/shapeworks/stats.py, Testing/UseCaseTests/UseCaseTests.cpp, install_shapeworks.bat, install_shapeworks.sh
@akenmorris/ @jadie1  can you upload the dataset to the portal [femur_stats.zip](https://github.com/SCIInstitute/ShapeWorks/files/6864554/femur_stats.zip)
This dataset has the shape model for femur with the group ids.
This PR includes the stats function to calculate the p-values for the group difference and includes a use case. 
To test the PR run - `python RunUseCase.py femur_pvalues`
=> Stats-pvalues for the group difference

Studio/src/Analysis/AnalysisTool.cpp, Studio/src/Visualization/Viewer.cpp
=> Fix scalar range

Examples/Python/ellipsoid_evaluate.py, Libs/Python/ShapeworksPython.cpp, Python/shapeworks/shapeworks/plot.py, Testing/UseCaseTests/UseCaseTests.cpp
=> Restructured ellipsoid evaluate use case

install_shapeworks.bat, install_shapeworks.sh
Hopefully fix #1467 by removing base env update, which I think is not needed
=> Fix GHA Windows (hopefully)

Libs/Groom/Groom.cpp, Libs/Image/Image.cpp, Testing/ImageTests/ImageTests.cpp, Testing/data/orientation_lpi.nrrd, Testing/data/orientation_rai.nrrd, Testing/data/orientation_rpi.nrrd, Testing/data/orientation_sal.nrrd, Testing/data/orientation_translated.nrrd
=> Change orientation to RAI if not already

install_shapeworks.bat, install_shapeworks.sh
=> Don't upgrade pip to latest, it exposes us to breaking changes

install_shapeworks.sh
I moved a few things to the "developer section".  This should eventually be expanded to resolve #884 as well.
I also added the missing `conda init` call as well.
=> Fix #1539, mac pkg install on a non-dev system asking to install dev tools

Libs/Common/Shapeworks.h, Libs/Mesh/Mesh.cpp, Testing/ImageTests/ImageTests.cpp, Testing/MeshTests/MeshTests.cpp
=> Removing epsEqualN and equalNSigDigits

install_shapeworks.bat, install_shapeworks.sh
Added versions for the following packages based on the Windows installation and my Linux build :
=> Pin package versions 

Applications/shapeworks/Commands.h, Applications/shapeworks/ImageCommands.cpp, Applications/shapeworks/shapeworks.cpp, Libs/Groom/Groom.cpp, Libs/Groom/Groom.h, Libs/Image/Image.cpp, Libs/Image/Image.h, Libs/Python/ShapeworksPython.cpp, Testing/ImageTests/ImageTests.cpp, Testing/PythonTests/PythonTests.cpp, Testing/PythonTests/isolate.py, Testing/data/isolate_input.nrrd, Testing/data/isolate_output.nrrd, Testing/shapeworksTests/isolate.sh, Testing/shapeworksTests/shapeworksTests.cpp
Fix #1591 by moving isolate from Groom to Image.
Added python interface, command line interface, testing data and all associated tests.
=> Move isolate from Groom to Image

Libs/Project/Project.cpp, Libs/Utils/StringUtils.cpp, Libs/Utils/StringUtils.h, Studio/src/Data/Session.cpp
This PR fixes some minor subject display name issues:
=> Studio display name

Testing/PythonTests/transform.py, Testing/data/transforms/imageTransformWithMeshTransform.nrrd, Testing/data/transforms/imageTransformWithoutMeshTransform.nrrd, Testing/data/transforms/meshTransformWithImageTransform.vtk, Testing/data/transforms/meshTransformWithoutImageTransform.vtk
The existing test for transform did not test anything so adding a proper PythonTest for transforms
=> Adding test for transform

Libs/Python/ShapeworksPython.cpp, Python/shapeworks/shapeworks/data.py
This PR fixes:
#1648 - Eigen assertions in ShapeWorksPython applyTransform
#1650 - Crash at the end of OptimizeTests.embedded_python_test
=> Fix debug automated test problems

Support/build_docs.sh, Support/deploy_docs.sh, docs/tools/ShapeWorksCommands.md, install_shapeworks.sh, mkdocs.yml
Part of the PR is to remove gh-pages so it can be constructed using the new versioning system. A copy of that branch called gh-pages_bak has been pushed as a backup.
#1575
=> Versioned docs

Examples/Python/femur_pvalues.py, Python/shapeworks/shapeworks/__init__.py, Python/shapeworks/shapeworks/plot.py, Python/shapeworks/shapeworks/stats.py
LDA added for group analysis in Python/shapeworks/shapeworks/stats.py and the required plot function. 
The functionality is demonstrated in femur_pvalues use case.This plot is produced:
=> Linear discriminant analysis for groups

Libs/Mesh/Mesh.cpp, Libs/Mesh/Mesh.h, Libs/Mesh/MeshWarper.cpp, Libs/Mesh/MeshWarper.h, Libs/Python/ShapeworksPython.cpp, Testing/MeshTests/MeshTests.cpp, Testing/PythonTests/meshinfo.py, Testing/PythonTests/warp.py
Add Mesh(points, faces) constructors from matrixes
=> Add python binding and unit tests.

.github/workflows/build-mac.yml, install_shapeworks.sh
=> Try to pin jinja to 3.0.3

docs/dev/contribute.md
=> Fix #1441 - add these items to git instructions in our documentation

Studio/src/Data/Preferences.cpp, Studio/src/Data/Preferences.h, Studio/src/Data/PreferencesWindow.cpp, Studio/src/Data/PreferencesWindow.ui, Studio/src/Visualization/ColorMap.cpp, Studio/src/Visualization/ColorMap.h, Studio/src/Visualization/Visualizer.cpp
=> Finish up new color map support

Examples/Python/deep_ssm.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/__init__.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/eval_utils.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/image_utils.py, docs/use-cases/deep-learning-based/deep-ssm-femur.md
This PR makes the following updates to the DeepSSM use case:
- Improved parameters for optimization and neural network training
- Applied cutting plane clipping when comparing predicted and true meshes for more accurate surface-to-surface distance analysis
- Improved documentation and added snapshots
=> DeepSSM updates

Libs/Mesh/MeshWarper.cpp, Libs/Mesh/MeshWarper.h
=> Copy of #1821

Libs/Project/Parameters.cpp, Libs/Project/Parameters.h, Libs/Project/Project.cpp, Libs/Project/Project.h, Libs/Project/ProjectUtils.cpp, Libs/Project/ProjectUtils.h, Libs/Project/Subject.cpp, Libs/Project/Subject.h, Libs/Project/Variant.cpp, Libs/Project/Variant.h
Submitting this PR to isolate formatting/style changes.
=> Reformat and re-style Libs/Project, no code changes

Studio/src/Analysis/AnalysisTool.cpp, Studio/src/Interface/ShapeWorksStudioApp.cpp, Studio/src/Visualization/Lightbox.cpp
Addresses:
* #1844
Also fixes VTK deprecation runtime warnings.
=> Fix Studio group functionality

Python/ShapeCohortGenPackage/ShapeCohortGen/CohortGenUtils.py
Cleaning up the ShapeCohortGen code so that the image size is correct to address issue #1878 
The following code can be used as a small test:
```
import shapeworks as sw
import ShapeCohortGen
out_dir = "generated_shapes/"
ss_generator = ShapeCohortGen.SupershapesCohortGenerator(out_dir)
meshFiles = ss_generator.generate(3, randomize_center=False, randomize_rotation=False)
segFiles = ss_generator.generate_segmentations(randomize_size=False, allow_on_boundary=False)
for segFile in segFiles:
img = sw.Image(segFile)
print(img.size())
```
This prints the same size for all three images.
Changing `randomize_size` to `True` results in images with different sizes.
=> Addressing issue #1878

Applications/shapeworks/Commands.cpp, Examples/Python/ellipsoid.py, Libs/Project/JsonProjectReader.cpp, Libs/Project/JsonProjectWriter.cpp, Python/shapeworks/shapeworks/utils.py
=> Fix #1869 - Optimize command not accepting .swproj files

.github/workflows/build-linux.yml, .github/workflows/build-mac.yml
=> Try adding devenv.sh for package scripts for Mac/Linux

Libs/Project/Project.cpp
=> Fix #1891 by checking for path existence before tryint to fix it up.

Libs/Optimize/Optimize.cpp, Libs/Optimize/Optimize.h, Libs/Optimize/OptimizeParameters.cpp, Libs/Optimize/OptimizeParameters.h
=> Fix #1893 by adding support for these two options

docs/getting-started/examples.md, docs/new/new-studio.md, docs/studio/studio-data.md
Addresses:
* #1863 
Also fixed some other mkdocs broken links.
=> Studio ffc docs

Libs/Common/Logging.cpp, Libs/Python/ShapeworksPython.cpp, Testing/ParticlesTests/CMakeLists.txt, Testing/data/python/project/project.py
=> Fix issue #1914, problem with subject_set_group_values

Libs/Project/ExcelProjectReader.cpp, Libs/Project/ExcelProjectReader.h
=> Fix #1915 - Loading a single sheet xlsx file should assume only sheet is the data sheet

Studio/src/Data/ExportUtils.cpp, Studio/src/Interface/ShapeWorksStudioApp.cpp, Studio/src/Interface/ShapeWorksStudioApp.h, Studio/src/Resources/Info.plist.in, Studio/src/main.cpp, Support/FileAssociation.nsh, Support/shapeworks.nsi
=> Studio file associations

Libs/Groom/Groom.cpp
=> Lock mutex during Groom::get_output_filename to fix #1944

Studio/src/Visualization/Viewer.cpp
=> Fix 1946 - crash picking particle

Libs/Project/Project.cpp, Studio/src/Interface/ShapeWorksStudioApp.cpp
=> Fix landmarks (#1954)

Studio/src/Data/ExportUtils.cpp, Studio/src/Interface/ShapeWorksStudioApp.cpp, Studio/src/Interface/ShapeWorksStudioApp.h, Studio/src/Visualization/Lightbox.cpp, Studio/src/Visualization/Lightbox.h, Studio/src/Visualization/StudioInteractorStyle.cpp, Studio/src/Visualization/StudioInteractorStyle.h, Studio/src/Visualization/Visualizer.cpp, Studio/src/Visualization/Visualizer.h
Adds feature to implement:
* #1653 
Also works around Qt bug for default file save extension
=> Right click export mesh 

Python/ShapeCohortGenPackage/ShapeCohortGen/CohortGenUtils.py
=> Fixed wrong iterate in shape cohort bounding box computation

Studio/src/Visualization/ParticleColors.cpp, Studio/src/Visualization/ParticleColors.h, Studio/src/Visualization/Viewer.cpp, Studio/src/Visualization/Visualizer.cpp
=> Try to fix #1965 by explicitly setting glyph actor opacity.

Libs/Analyze/Analyze.cpp, Libs/Analyze/Analyze.h, Testing/data/shapeworksTests/analyze/mean_shape_0.baseline.vtk, Testing/data/shapeworksTests/analyze/pca_mode_1_domain_0_minus_0.4.baseline.vtk
Initialize mesh warper from Analyze class
Resolves
* #1977 
More of AnalysisTool needs to be extracted and put into Analyze class.
=> Initialize mesh warper from Analyze class

docs/workflow/parameters.md
=> Add swproj docs

Libs/Project/Project.cpp
=> Fix #1976, domain type switching bug

docs/use-cases/mesh-based/hip.md
Added gifs for the shape model
=> Doc update for hip use case

Libs/Optimize/Optimize.cpp
Switch message "Shapeworks: TBB using 16 threads" to a debug log macro
=> Switch threading message to SW_DEBUG

install_shapeworks.sh
Fixes:
* #2001 
This is just kicking the can down the road a bit, but fixes things for now.
=> Fix conda install

.github/workflows/build-linux-debug.yml, .github/workflows/build-linux.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml
See https://docs.github.com/en/actions/using-jobs/using-concurrency
=> Cancel previous workflow on subsequent pushes.

Libs/Analyze/Particles.h
=> Fix #2024 by fixing uninitialized alignment_type member

Libs/Project/Parameters.cpp, Libs/Project/Parameters.h, Libs/Project/Variant.cpp, Libs/Project/Variant.h, Libs/Python/ShapeworksPython.cpp, Testing/data/python/project/project.py
Internal version of #2058 to allow GitHub Actions.
=> Fix Parameters with Python binding.

Studio/CMakeLists.txt, Support/package_windows.sh
for the user to have to install the visual studio distributables.
=> Try installing msvcp140.dll and vcruntime140.dll to eliminate the need

Libs/Optimize/Constraints/Constraints.cpp
=> Fix #2090 planes without 3 points

.github/workflows/build-linux-debug.yml, Python/shapeworks/shapeworks/network_analysis.py, Studio/DeepSSM/DeepSSMJob.cpp, Studio/Job/GroupPvalueJob.cpp, Studio/Job/NetworkAnalysisJob.cpp, Studio/Python/PythonWorker.cpp, docs/studio/deepssm-in-studio.md
Fix Python multiprocessing on windows.
Also enable parallel data augmentation in Studio (see #1136)
=> Fix windows python multiprocessing

Libs/Analyze/Particles.cpp, Libs/Analyze/Particles.h, Libs/Analyze/Shape.cpp, Libs/Analyze/Shape.h, Studio/Analysis/AnalysisTool.cpp
Fix #2134 
* #2134 
This PR fixes procrustes scaling in analysis when using multiple domains.
=> Fix procrustes scaling for multiple domains

Libs/Analyze/Shape.cpp, Libs/Analyze/Shape.h, Libs/Project/Project.cpp, Libs/Project/ProjectReader.cpp, Libs/Project/ProjectUtils.cpp, Libs/Project/Subject.cpp, Libs/Project/Subject.h, Studio/Data/DataTool.cpp, Studio/Data/DataTool.h, Studio/Data/DataTool.ui, Studio/Data/Session.cpp, Studio/Data/Session.h, Studio/Visualization/Viewer.cpp, Studio/Visualization/Viewer.h, Studio/Visualization/Visualizer.cpp, Studio/Visualization/Visualizer.h
=> #2160 subject notes

Studio/Analysis/AnalysisTool.cpp, Studio/Job/ShapeScalarJob.cpp
=> Fix bug where "Inconsistent number of particles" error is raised when using "Scalar Only" mode.

Libs/Mesh/MeshComputeThickness.cpp, Libs/Mesh/MeshComputeThickness.h, Studio/Data/Session.cpp, Studio/Data/Session.h, Studio/Interface/ShapeWorksStudioApp.cpp, Studio/Interface/ShapeWorksStudioApp.ui, Studio/Visualization/SliceView.cpp, Studio/Visualization/SliceView.h, Studio/Visualization/Viewer.cpp
=> Resolve #2177 by adding the new feature to display the thickness as an inner surface on slices

Studio/Visualization/SliceView.cpp, Studio/Visualization/Viewer.cpp
=> Fix #2184 - image volume viewers don't update past the number of viewers

Libs/Mesh/Mesh.cpp, Libs/Python/ShapeworksPython.cpp, Testing/MeshTests/MeshTests.cpp, Testing/OptimizeTests/OptimizeTests.cpp
=> Bug fix Mesh::interpolateFieldAtPoint() and add Python binding.

Libs/Analyze/Shape.cpp, Libs/Image/Image.cpp, Libs/Image/Image.h, Libs/Mesh/Mesh.cpp, Libs/Mesh/Mesh.h, Libs/Mesh/MeshComputeThickness.cpp, Libs/Mesh/MeshComputeThickness.h, Testing/data/thickness/thickness.vtk
=> #2189 internal image summary

Libs/Analyze/Particles.cpp, Libs/Analyze/Particles.h, Libs/Particles/ShapeEvaluation.cpp, Studio/Analysis/AnalysisTool.cpp, Studio/Analysis/AnalysisTool.h, Studio/Analysis/AnalysisTool.ui, Studio/Analysis/ParticleAreaPanel.cpp, Studio/Interface/ShapeWorksStudioApp.cpp, Studio/Utils/AnalysisUtils.cpp, Studio/Utils/AnalysisUtils.h
Add stats, table and boxplot of scalar/predicted diff.
=> 2218 scalar evaluation

Examples/Python/deep_ssm.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/__init__.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/eval_utils.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/train_viz.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/trainer.py, Python/shapeworks/shapeworks/__init__.py, Python/shapeworks/shapeworks/utils.py
Resolve #2226 
This changes the training to additionally add .vtk files with scalars (deepssm_error) already interpolated to the mesh.
=> 2226 deepssm meshes

Examples/Python/deep_ssm.py, Python/DataAugmentationUtilsPackage/DataAugmentationUtils/DataAugmentation.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/__init__.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/run_utils.py, Python/DeepSSMUtilsPackage/DeepSSMUtils/trainer.py, Python/shapeworks/shapeworks/utils.py
Resolve #2230 -  DeepSSM Augmentation should write VTK files in addition to particles
=> Resolve #2230 -  DeepSSM Augmentation should write VTK files in addition to particles

Python/DataAugmentationUtilsPackage/DataAugmentationUtils/Embedder.py, Studio/DeepSSM/DeepSSMTool.cpp, Studio/DeepSSM/DeepSSMTool.h
=> DeepSSM / Studio Augmentation Issues

Studio/Visualization/Viewer.cpp, Studio/Visualization/Visualizer.cpp
=> Fix #2239 - arrows and colors for group diff

Studio/Analysis/AnalysisTool.cpp, Studio/Analysis/AnalysisTool.h
* #2241
Ability to copy table values from difference to predicted scalar table in 'samples' table of Analysis
=> Address #2241 - Ability to copy table values from difference to predicted scalar table in 'samples' table of Analysis

.github/workflows/build-linux-debug.yml, .github/workflows/build-linux.yml, .github/workflows/build-mac-arm64.yml, .github/workflows/build-mac.yml, .github/workflows/build-windows.yml, .github/workflows/download_test_data.sh, .github/workflows/gha_conda.sh, .github/workflows/gha_deps.sh
Fix GitHub Actions.  Remove remote cache.
=> Fix Github Actions

install_shapeworks.bat, python_requirements.txt
=> Fix install_shapeworks.bat

Examples/Python/Data/femur_pvalues.zip, Examples/Python/Data/supershapes_1mode_contour.zip, Examples/Python/ellipsoid_fd.py, Examples/Python/femur_pvalues.py, Examples/Python/supershapes_1mode_contour.py, Studio/Analysis/AnalysisTool.cpp
Fix cloud portal download and tests
=> Dataset Test updates

Python/shapeworks/shapeworks/utils.py
=> Fix #2298 - check all mesh types

Studio/Analysis/AnalysisTool.cpp
=> Fix #2306 by setting stats_ready_ false earlier and checking for it

.github/workflows/gha_conda.sh, python_requirements.txt
=> Fix #2308 again in a different way by only upgrading the python vtk as minimally as possible (to 9.2.2)

Python/DeepSSMUtilsPackage/DeepSSMUtils/run_utils.py
=> Fix #2315 by causing the ITK libraries to load at a time when other threads won't be doing file I/O.

Studio/Groom/GroomTool.cpp, Studio/Groom/GroomTool.h
* #2263 
Add block signals to fix #2263
=> Add block singals to fix #2263

Libs/Analyze/MeshGenerator.cpp, Libs/Image/Image.cpp, Libs/Image/Image.h, Testing/ImageTests/ImageTests.cpp, Testing/MeshTests/MeshTests.cpp
The code I had added to handle the segmentations was only meant for segmentations, not distance transforms.
=> Fix #2338 - Mesh generation from distance transforms.

Libs/Analyze/Shape.cpp
=> Fix #2335 - Crash on exporting mesh from computed shape

Libs/Mesh/Mesh.cpp
* #2405 
Remove extra unused curvature computation code.
=> Remove unused mesh curvature code (#2405)

Libs/Groom/Groom.cpp
* #2404 
We now check that the number of landmarks are not zero and are equal for all subjects/domains.
=> Fix #2404, crash on landmark-based alignment when no landmarks are present.

Support/vtk-9.5.patch, build_dependencies.sh
The VTK patch has to be updated for 9.5
I really need to submit these bugs and fixes upstream.
=> Fix vtk patch for 9.5

Libs/Mesh/CMakeLists.txt, Libs/Optimize/CMakeLists.txt, cmake/FindGEOMETRYCENTRAL.cmake
=> Add support for suitesparse when detected by geometry central.

Libs/Groom/Groom.cpp, Libs/Image/Image.cpp, Libs/Image/Image.h
* #2423
Fix #2423 by resampling oblique images first.
=> Fix #2423 by resampling oblique images first.

.github/workflows/build-linux-debug.yml, .github/workflows/gha_deps.sh
Try to free up space for linux debug github actions runner
=> Try to free up space for linux debug github actions runner
